### ISSUE TITLE
Helligkeit beim Bewegungsmelder fehlt

### ISSUE THREAD

**Issue by nicoh88** [kdietrich/homebridge-devolo#1]
Hallo Kevin,

bitte die Helligkeit des Bewegungsmelder mit auslesen.

Devolo Bewegungsmelder = max. 500 Lux
1 Lux = 0,2%

Gruß Nico

**Comment by kdietrich** [comment]
Fixed in the next release with https://github.com/kdietrich/homebridge-devolo/commit/4a395a2b0bc97c8038a3d0873df8778765215649.
