### ISSUE TITLE
Gerätenamen in der Log

### ISSUE THREAD

**Issue by nicoh88** [kdietrich/homebridge-devolo#11]
Hi Kevin,

es wäre ganz nett, wenn man den in Devolo vergebenen Gerätenamen in der Homebridge Log sehen würde. Siehe Screenshot.

![bildschirmfoto 2017-04-24 um 14 41 31](https://cloud.githubusercontent.com/assets/264264/25337472/48d8bac0-28fc-11e7-9dd6-1bffa88b8f34.png)

Gruß Nico

**Comment by kdietrich** [comment]
Ab v0.1.5 wird der Gerätename mit angezeigt.
