### ISSUE TITLE
Install 0.1.4 dev version

### ISSUE THREAD

**Issue by KiboOst** [kdietrich/homebridge-devolo#13]
I would use the rules and scenes in 0.1.4 dev version but can't manage to install it.

`npm show homebridge-devolo@* version`

return 0.1.0, 0.1.1, 0.1.2, 0.1.3 but no 0.1.4

Any insight ?

**Comment by KiboOst** [comment]
Ok, got it calling directly:
`npm install -g https://github.com/kdietrich/homebridge-devolo`

I also added ruleWhitelist and sceneWhitelist in config.json!

And it works!

Kevin, if you need I have all necessary stuff to add support for:
siren
shutter
wall:control
fibaro smoke detector

Let me know!

**Comment by KiboOst** [comment]
Well, after a few hours of all working nice, seems broken:

HBDevoloPlatform > Error: connect ECONNREFUSED 192.168.0.25:80

**Comment by KiboOst** [comment]
Ok, since it is running, I have lot of Devolo central reboot, approx every hour when we are at home (more movements and such I guess) with such messages:

`Error: socket hang up
    at createHangUpError (_http_client.js:302:15)
    at Socket.socketCloseListener (_http_client.js:334:23)
    at emitOne (events.js:101:20)
    at Socket.emit (events.js:191:7)
    at TCP._handle.close [as _onclose] (net.js:511:12) code: 'ECONNRESET' }

Cannot Execute in Platform State STOPPING

Error: connect ECONNREFUSED 192.168.0.25:80
    at Object.exports._errnoException (util.js:1050:11)
    at exports._exceptionWithHostPort (util.js:1073:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1093:14)
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect',

Cannot Execute in Platform State STARTING`

I shut it down, waiting for next stable version ;-)

**Comment by KiboOst** [comment]
Another error which may interest you, just after a reboot of DHC:

Cannot Execute in Platform State INITIALIZING[39m[22m
[37m[7/5/2017, 2:37:30 AM][39m [36m[Devolo][39m [1m[31mSession is not available[39m[22m
[37m[7/5/2017, 2:37:30 AM][39m [36m[Devolo][39m Fetching new session...
[37m[7/5/2017, 2:37:40 AM][39m [36m[Devolo][39m Session successfully renewed.
[37m[7/5/2017, 2:37:46 AM][39m [36m[Devolo][39m [1m[31mTypeError: Cannot read property 'forEach' of undefined
at /usr/local/lib/node_modules/homebridge-devolo/node_modules/node-devolo/dist/Devolo.js:130:18
at /usr/local/lib/node_modules/homebridge-devolo/node_modules/node-devolo/dist/DevoloApi.js:183:17
at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/homebridge-devolo/node_modules/node-devolo/dist/DevoloApi.js:64:21)
at emitNone (events.js:91:20)
at IncomingMessage.emit (events.js:188:7)
at endReadableNT (_stream_readable.js:975:12)
at _combinedTickCallback (internal/process/next_tick.js:80:11)
at process._tickCallback (internal/process/next_tick.js:104:9)

**Comment by kdietrich** [comment]
Thanks for reporting - I'll look into it.

**Comment by KiboOst** [comment]
No problem. Will you ad support for shutters/qubinos ? Drop me a mail or have a look at php devolo source code

**Comment by KiboOst** [comment]
Just installed a new raspbian with last 0.1.4-dev (with new performance optimization) to try if rPi won't make my DHC reboot like Synology Docker, and here is a new error:

/usr/lib/node_modules/homebridge-devolo/node_modules/node-devolo/dist/DevoloDevice.js:89
Jul 06 15:05:31 raspberrypi homebridge[6699]: throw new Error('Device has no suitable sensor.');
Jul 06 15:05:31 raspberrypi homebridge[6699]: ^
Jul 06 15:05:31 raspberrypi homebridge[6699]: Error: Device has no suitable sensor.
Jul 06 15:05:31 raspberrypi homebridge[6699]: at SwitchMeterDevice.Device.getState (/usr/lib/node_modules/homebridge-devolo/node_modules/node-devolo/dist/DevoloDevice.js:89:23)
Jul 06 15:05:31 raspberrypi homebridge[6699]: at HBDevoloSwitchMeterDevice.getSwitchState (/usr/lib/node_modules/homebridge-devolo/dist/devices/HBDevoloSwitchMeterDevice.js:75:44)
Jul 06 15:05:31 raspberrypi homebridge[6699]: at emitThree (events.js:116:13)
Jul 06 15:05:31 raspberrypi homebridge[6699]: at Characteristic.On.emit (events.js:197:7)
Jul 06 15:05:31 raspberrypi homebridge[6699]: at Characteristic.On.Characteristic.getValue (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Characteristic.js:129:10)
Jul 06 15:05:31 raspberrypi homebridge[6699]: at Bridge.<anonymous> (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:627:20)
Jul 06 15:05:31 raspberrypi homebridge[6699]: at Array.forEach (native)
Jul 06 15:05:31 raspberrypi homebridge[6699]: at Bridge.Accessory._handleGetCharacteristics (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:591:8)
Jul 06 15:05:31 raspberrypi homebridge[6699]: at emitMany (events.js:127:13)
Jul 06 15:05:31 raspberrypi homebridge[6699]: at HAPServer.emit (events.js:204:7)
Jul 06 15:05:31 raspberrypi systemd[1]: homebridge.service: main process exited, code=exited, status=1/FAILURE
Jul 06 15:05:31 raspberrypi systemd[1]: Unit homebridge.service entered failed state.

**Comment by KiboOst** [comment]
A bit more info, runing -D:
[7/6/2017, 4:34:39 PM] [Devolo] HBDevoloMotionDevice > Hearbeat
[7/6/2017, 4:34:39 PM] [Devolo] HBDevoloMotionDevice > Hearbeat
[7/6/2017, 4:34:39 PM] [Devolo] HBDevoloSwitchMeterDevice (hdm:ZWave:D8F7DDE2/18) > Hearbeat
[7/6/2017, 4:34:39 PM] [Devolo] HBDevoloSwitchMeterDevice (hdm:ZWave:D8F7DDE2/35) > Hearbeat
[7/6/2017, 4:34:39 PM] [Devolo] Error: Device has no suitable sensor.
    at SwitchMeterDevice.Device.getState (/usr/lib/node_modules/homebridge-devolo/node_modules/node-devolo/dist/DevoloDevice.js:89:23)
    at HBDevoloSwitchMeterDevice.heartbeat (/usr/lib/node_modules/homebridge-devolo/dist/devices/HBDevoloSwitchMeterDevice.js:47:37)
    at /usr/lib/node_modules/homebridge-devolo/dist/HBDevoloCentralUnit.js:76:39
    at Array.forEach (native)
    at /usr/lib/node_modules/homebridge-devolo/dist/HBDevoloCentralUnit.js:68:29
    at /usr/lib/node_modules/homebridge-devolo/node_modules/node-devolo/dist/Devolo.js:219:17
    at /usr/lib/node_modules/homebridge-devolo/node_modules/node-devolo/dist/DevoloApi.js:190:13
    at IncomingMessage.<anonymous> (/usr/lib/node_modules/homebridge-devolo/node_modules/node-devolo/dist/DevoloApi.js:64:21)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:188:7)


Always happens on D8F7DDE2/35, wich is a common wall plug (v1) with devolo.Meter:hdm:ZWave:D8F7DDE2/35 and devolo.BinarySwitch:hdm:ZWave:D8F7DDE2/35
"model": "devolo.model.Wall:Plug:Switch:and:Meter"

Strange is that the /18 is same wal plug model, in same zone
Have tried deleting /persist folder, same thing.

**Comment by KiboOst** [comment]
I can also confirm that Homebridge make my central rebooting.
No homebridge since yesterday, no reboot. It never done that anyway, but it could be Devolo server having problems, but only happens when homebridge runs.
Anyway, can't run it anymore as last 0.1.4dev optimization broke it.

**Comment by kdietrich** [comment]
Thanks for your research. I'll look into it after my one week vacation.

**Comment by KiboOst** [comment]
Ok thanks, if you can add shutters support, would be amazing also ;-)

**Comment by KiboOst** [comment]
Had a look (rapidly) and it seems the device constructor doesn't pass the sensors (elementUIDS)...

Does this version work on your dhc ??

**Comment by KiboOst** [comment]
Ok, exact same thing, homebridge on a dedicated raspberry make my central unit rebooting every few hours... Will wait some more stable version.

**Comment by kdietrich** [comment]
I'm going to publish some fixes optimizing performance in the next couple of days. I'm happy to hear your feedback. Stay tuned!

**Comment by KiboOst** [comment]
Yes, all wall plugs official ones, v1

**Comment by KiboOst** [comment]
Hi
Any idea about a new version fixing Devolo Gateway reboot ?

Any news on qubino shutters support ? Have a look at my php devolo, all needed is there, or drop me an email.

Cheers

**Comment by kdietrich** [comment]
Sorry, I was busy the last days and couldn't find time to push said update. I'll push some fixes at the start of next week.

**Comment by kdietrich** [comment]
Hi @KiboOst, please try the latest master and let me know if your issues are fixed.

**Comment by KiboOst** [comment]
[9/11/2017, 5:12:05 PM] ====================
[9/11/2017, 5:12:05 PM] ERROR LOADING PLUGIN homebridge-devolo:
[9/11/2017, 5:12:05 PM] Error: Cannot find module 'ws'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/lib/node_modules/homebridge-devolo/node_modules/node-devolo/dist/DevoloApi.js:2:17)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
[9/11/2017, 5:12:05 PM] ====================
[9/11/2017, 5:12:05 PM] No plugins found. See the README for information on installing plugins.
[9/11/2017, 5:12:05 PM] Loaded config.json with 0 accessories and 1 platforms.
[9/11/2017, 5:12:05 PM] ---
[9/11/2017, 5:12:05 PM] Loading 1 platforms...
/usr/lib/node_modules/homebridge/lib/api.js:122
      throw new Error("The requested platform '" + name + "' was not registered by any plugin.");
      ^

Error: The requested platform 'Devolo' was not registered by any plugin.
    at API.platform (/usr/lib/node_modules/homebridge/lib/api.js:122:13)
    at Server._loadPlatforms (/usr/lib/node_modules/homebridge/lib/server.js:284:45)
    at Server.run (/usr/lib/node_modules/homebridge/lib/server.js:80:36)
    at module.exports (/usr/lib/node_modules/homebridge/lib/cli.js:40:10)
    at Object.<anonymous> (/usr/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)

**Comment by ramsnerm** [comment]
Installing the plugin with the standard command didn't fetch v0.1.5-dev (only installed 0.1.4)
`npm install -g homebridge-devolo`

Instead of this I had to use
`npm install -g https://github.com/kdietrich/homebridge-devolo#a5cf48f1c0ed818440c29ca48335874effc24d32`

Starting afterwards homebridge I had the same error message as @KiboOst ([see issue](https://github.com/kdietrich/homebridge-devolo/issues/13)).

To solve it I had to install
`npm install -g ws`

This allowed me now to start it, but my [original problem](https://github.com/kdietrich/homebridge-devolo/issues/16) still exists so I had to apply my "fix" again:
modifying line 133 of the file
/usr/local/lib/node_modules/homebridge-devolo/node_modules/node-devolo/dist/Devolo.js

`if (item.UID.indexOf('virtual:device') > -1 **|| item.properties.deviceModelUID == null**) { continue; //not supported yet }`

**Comment by KiboOst** [comment]
Ok, with ws module it works
npm install -g ws

**Comment by KiboOst** [comment]
Have tons of 'couldn't find sensor messages' per seconds...
Sep 11 17:57:23 raspberrypi homebridge[25091]: COULDNT FIND SENSOR: devolo.DeviceEvents
Sep 11 17:57:23 raspberrypi homebridge[25091]: COULDNT FIND SENSOR: devolo.DeviceEvents
Sep 11 17:57:23 raspberrypi homebridge[25091]: COULDNT FIND RULE PROPERTY: newData
Sep 11 17:57:39 raspberrypi homebridge[25091]: COULDNT FIND SENSOR: devolo.BinarySensor:hdm:ZWave:D8F7DDE2/12
Sep 11 17:57:39 raspberrypi homebridge[25091]: COULDNT FIND SENSOR: devolo.BinarySensor:hdm:ZWave:D8F7DDE2/12
Sep 11 17:57:39 raspberrypi homebridge[25091]: COULDNT FIND SENSOR: devolo.BinarySensor:hdm:ZWave:D8F7DDE2/12
Sep 11 17:57:39 raspberrypi homebridge[25091]: COULDNT FIND SENSOR: devolo.BinarySensor:hdm:ZWave:D8F7DDE2/12
Sep 11 17:57:39 raspberrypi homebridge[25091]: COULDNT FIND SENSOR: devolo.BinarySensor:hdm:ZWave:D8F7DDE2/12
Sep 11 17:57:39 raspberrypi homebridge[25091]: COULDNT FIND SENSOR: devolo.BinarySensor:hdm:ZWave:D8F7DDE2/12

rule property battery level ???????????????
Sep 11 17:58:05 raspberrypi homebridge[25091]: COULDNT FIND SENSOR: hdm:ZWave:D8F7DDE2/61
Sep 11 17:58:05 raspberrypi homebridge[25091]: COULDNT FIND RULE PROPERTY: batteryLevel

**Comment by KiboOst** [comment]
Didn't work long...

Sep 11 18:03:44 raspberrypi homebridge[25213]: (node:25213) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 message listeners added. Use emitter.setMaxListeners() to increase limit
Sep 11 18:03:44 raspberrypi homebridge[25213]: [9/11/2017, 6:03:44 PM] Homebridge is running on port 51826.
Sep 11 18:03:47 raspberrypi homebridge[25213]: /usr/lib/node_modules/homebridge-devolo/node_modules/node-devolo/dist/DevoloDevice.js:134
Sep 11 18:03:47 raspberrypi homebridge[25213]: throw new Error('Device has no suitable sensor.');
Sep 11 18:03:47 raspberrypi homebridge[25213]: ^
Sep 11 18:03:47 raspberrypi homebridge[25213]: Error: Device has no suitable sensor.
Sep 11 18:03:47 raspberrypi homebridge[25213]: at SwitchMeterDevice.Device.getState (/usr/lib/node_modules/homebridge-devolo/node_modules/node-devolo/dist/DevoloDevice.js:134:23)
Sep 11 18:03:47 raspberrypi homebridge[25213]: at HBDevoloSwitchMeterDevice.getSwitchState (/usr/lib/node_modules/homebridge-devolo/dist/devices/HBDevoloSwitchMeterDevice.js:62:44)
Sep 11 18:03:47 raspberrypi homebridge[25213]: at emitThree (events.js:116:13)
Sep 11 18:03:47 raspberrypi homebridge[25213]: at Characteristic.On.emit (events.js:197:7)
Sep 11 18:03:47 raspberrypi homebridge[25213]: at Characteristic.On.Characteristic.getValue (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Characteristic.js:142:10)
Sep 11 18:03:47 raspberrypi homebridge[25213]: at Bridge.<anonymous> (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:706:20)
Sep 11 18:03:47 raspberrypi homebridge[25213]: at Array.forEach (native)
Sep 11 18:03:47 raspberrypi homebridge[25213]: at Bridge.Accessory._handleGetCharacteristics (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:670:8)
Sep 11 18:03:47 raspberrypi homebridge[25213]: at emitMany (events.js:127:13)
Sep 11 18:03:47 raspberrypi homebridge[25213]: at HAPServer.emit (events.js:204:7)
Sep 11 18:03:47 raspberrypi systemd[1]: homebridge.service: main process exited, code=exited, status=1/FAILURE
Sep 11 18:03:47 raspberrypi systemd[1]: Unit homebridge.service entered failed state.

**Comment by KiboOst** [comment]
Sep 11 18:11:55 raspberrypi homebridge[25244]: /usr/lib/node_modules/homebridge-devolo/node_modules/node-devolo/dist/DevoloDevice.js:134
Sep 11 18:11:55 raspberrypi homebridge[25244]: throw new Error('Device has no suitable sensor.');
Sep 11 18:11:55 raspberrypi homebridge[25244]: ^
Sep 11 18:11:55 raspberrypi homebridge[25244]: Error: Device has no suitable sensor.
Sep 11 18:11:55 raspberrypi homebridge[25244]: at SwitchMeterDevice.Device.getState (/usr/lib/node_modules/homebridge-devolo/node_modules/node-devolo/dist/DevoloDevice.js:134:23)
Sep 11 18:11:55 raspberrypi homebridge[25244]: at HBDevoloSwitchMeterDevice.getSwitchState (/usr/lib/node_modules/homebridge-devolo/dist/devices/HBDevoloSwitchMeterDevice.js:62:44)
Sep 11 18:11:55 raspberrypi homebridge[25244]: at emitThree (events.js:116:13)
Sep 11 18:11:55 raspberrypi homebridge[25244]: at Characteristic.On.emit (events.js:197:7)
Sep 11 18:11:55 raspberrypi homebridge[25244]: at Characteristic.On.Characteristic.getValue (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Characteristic.js:142:10)
Sep 11 18:11:55 raspberrypi homebridge[25244]: at Bridge.<anonymous> (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:706:20)
Sep 11 18:11:55 raspberrypi homebridge[25244]: at Array.forEach (native)
Sep 11 18:11:55 raspberrypi homebridge[25244]: at Bridge.Accessory._handleGetCharacteristics (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:670:8)
Sep 11 18:11:55 raspberrypi homebridge[25244]: at emitMany (events.js:127:13)
Sep 11 18:11:55 raspberrypi homebridge[25244]: at HAPServer.emit (events.js:204:7)
Sep 11 18:11:55 raspberrypi systemd[1]: homebridge.service: main process exited, code=exited, status=1/FAILURE
Sep 11 18:11:55 raspberrypi systemd[1]: Unit homebridge.service entered failed state.

**Comment by ramsnerm** [comment]
I have simliar errors:
COULDNT FIND SENSOR: devolo.BinarySwitch:hdm:ZWave:EADFD80F/8

**Comment by KiboOst** [comment]
Yes and it finnally crash after a few minute

**Comment by KiboOst** [comment]
See this:
https://github.com/kdietrich/homebridge-devolo/issues/18

;-)
