### ISSUE TITLE
Nicht Devolo Geräte (z-Wave) hinzufügen

### ISSUE THREAD

**Issue by ramsnerm** [kdietrich/homebridge-devolo#14]
**Hallo,**

Zuerst einmal ein ganz **Dickens Lob und DANKE** für die tolle Arbeit. Mit dieser Lösung kann ich endlich die verschiedenen Geräte dich ansonsten mit mehreren Apps steuere zusammenschalten und auf dem Apple Home Frontend anzeigen. 

Jetzt habe ich aber auf der Devolo Zentrale auch nicht Devolo Geräte (zB z-wave Schalter von Busch und Jäger) angemeldet.

Wie kann ich diese übertragen oder ist dies nur programmtechnisch möglich. Welche Angaben würdest du ggf. dafür benötigen?

DANKE für eine Antwort
_LG / Martin_

**Comment by kdietrich** [comment]
Hallo Martin,

danke für dein Lob & Feedback. Der Z-Wave Schalter von Busch und Jäger müsste baugleich mit dem Schalter von Devolo sein. Leider wird letzter momentan noch nicht unterstützt, ist aber fest in Planung für eine spätere Version!

**Comment by ramsnerm** [comment]
Hallo,
DANKE für das Feedback. Ich wünsch dir noch einen schönes Wochenende.

LG / Martin

**Comment by kdietrich** [comment]
@ramsnerm Könntest du auf die neueste Version updaten und die hier beschrieben Schritte durchführen: https://github.com/kdietrich/homebridge-devolo#support-of-new-devices Die damit erstellte Datei kannst du anschließend in diesem Issue hochladen. Diese dient mir als Vorlage für die Geräteintegration.
