### ISSUE TITLE
Scenes seen as switches

### ISSUE THREAD

**Issue by KiboOst** [kdietrich/homebridge-devolo#15]
Is it normal that in 0.1.4, scenes in whitelist are indeed there, but seen as switches ? They don't appear as scenes like on your screen for example.

**Comment by kdietrich** [comment]
This is perfectly normal. AFAIK it's not possible to directly add scenes via Homebridge. The Devolo scene will be added as a device (switch) and you can add the scene directly in Apples Home app.

**Comment by KiboOst** [comment]
Yes this is what I have done, thanks for confirmation. You may add doc about whitelist in config like heartbeat for 0.1.4 ?
