### ISSUE TITLE
shutter support

### ISSUE THREAD

**Issue by KiboOst** [kdietrich/homebridge-devolo#17]
homebridge[25213]: Device devolo.model.Shutter is not supported (yet). Open an issue on github and ask for adding it.

All necessary sensors and requests can be found here:
https://github.com/KiboOst/php-devoloDHC

**Comment by KiboOst** [comment]
Here is a complete debug json for qubino/devolo flush shutter module

[qubinoShutter.zip](https://github.com/kdietrich/homebridge-devolo/files/1295587/qubinoShutter.zip)

**Comment by kdietrich** [comment]
Thanks for your log file! Shutters are supported in v0.1.5.

**Comment by KiboOst** [comment]
Many thanks Kevin, amazing work and all running fine and stable here !!
