### ISSUE TITLE
v0.1.5-dev broken ?

### ISSUE THREAD

**Issue by KiboOst** [kdietrich/homebridge-devolo#18]
npm update homebridge-devolo
-> installed 0.1.5
First failed, seems ws is a new dependency so installed it

Now, it works for a minute or two, sending tons of ' COULDNT FIND SENSOR:' message finally showing:
(node:1112) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 message listeners added. Use emitter.setMaxListeners() to increase limit

 typical log:
Sep 11 21:22:36 nodejs[1112]: *** WARNING *** The program 'nodejs' uses the Apple Bonjour compatibility layer of Avahi.
Sep 11 21:22:36 nodejs[1112]: *** WARNING *** Please fix your application to use the native API of Avahi!
Sep 11 21:22:36 nodejs[1112]: *** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=nodejs>
Sep 11 21:22:36 nodejs[1112]: *** WARNING *** The program 'nodejs' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
Sep 11 21:22:36 nodejs[1112]: *** WARNING *** Please fix your application to use the native API of Avahi!
Sep 11 21:22:36 nodejs[1112]: *** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=nodejs&f=DNSServiceRegister>
Sep 11 21:22:36 homebridge[1112]: *** WARNING *** Please fix your application to use the native API of Avahi!
Sep 11 21:22:36 homebridge[1112]: *** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=nodejs>
Sep 11 21:22:36 homebridge[1112]: *** WARNING *** The program 'nodejs' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
Sep 11 21:22:36 homebridge[1112]: *** WARNING *** Please fix your application to use the native API of Avahi!
Sep 11 21:22:36 homebridge[1112]: *** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=nodejs&f=DNSServiceRegister>
Sep 11 21:22:39 homebridge[1112]: [9/11/2017, 9:22:39 PM] Loaded plugin: homebridge-devolo
Sep 11 21:22:39 homebridge[1112]: [9/11/2017, 9:22:39 PM] Registering platform 'homebridge-devolo.Devolo'
Sep 11 21:22:39 homebridge[1112]: [9/11/2017, 9:22:39 PM] ---
Sep 11 21:22:39 homebridge[1112]: [9/11/2017, 9:22:39 PM] Loaded config.json with 0 accessories and 1 platforms.
Sep 11 21:22:39 homebridge[1112]: [9/11/2017, 9:22:39 PM] ---
Sep 11 21:22:39 homebridge[1112]: [9/11/2017, 9:22:39 PM] Loading 1 platforms...
Sep 11 21:22:39 homebridge[1112]: [9/11/2017, 9:22:39 PM] [Devolo] Initializing Devolo platform...
Sep 11 21:22:39 homebridge[1112]: [9/11/2017, 9:22:39 PM] [Devolo] HBDevoloPlatform > Searching for Devolo Central Unit.
Sep 11 21:22:39 homebridge[1112]: Trying to connect to socket.
Sep 11 21:22:39 homebridge[1112]: Websocket open
Sep 11 21:22:39 homebridge[1112]: [9/11/2017, 9:22:39 PM] [Devolo] HBDevoloPlatform > Central Unit found.
Sep 11 21:22:41 homebridge[1112]: Device devolo.model.Siren is not supported (yet). Open an issue on github and ask for adding it.
Sep 11 21:22:41 homebridge[1112]: Device devolo.model.Siren is not supported (yet). Open an issue on github and ask for adding it.
Sep 11 21:22:41 homebridge[1112]: Device devolo.model.Shutter is not supported (yet). Open an issue on github and ask for adding it.
Sep 11 21:22:41 homebridge[1112]: Device devolo.model.Unknown:Device is not supported (yet). Open an issue on github and ask for adding it.
Sep 11 21:22:41 homebridge[1112]: Device devolo.model.Wall:Control is not supported (yet). Open an issue on github and ask for adding it.
Sep 11 21:22:41 homebridge[1112]: Device devolo.model.Shutter is not supported (yet). Open an issue on github and ask for adding it.
Sep 11 21:22:41 homebridge[1112]: Device devolo.model.Wall:Control is not supported (yet). Open an issue on github and ask for adding it.
Sep 11 21:22:41 homebridge[1112]: Device devolo.model.Shutter is not supported (yet). Open an issue on github and ask for adding it.
Sep 11 21:22:41 homebridge[1112]: Device devolo.model.Unknown:Device is not supported (yet). Open an issue on github and ask for adding it.
Sep 11 21:22:41 homebridge[1112]: Device devolo.model.Wall:Control is not supported (yet). Open an issue on github and ask for adding it.
Sep 11 21:22:41 homebridge[1112]: Device devolo.model.Wall:Control is not supported (yet). Open an issue on github and ask for adding it.
Sep 11 21:22:41 homebridge[1112]: Device devolo.model.Shutter is not supported (yet). Open an issue on github and ask for adding it.
Sep 11 21:22:41 homebridge[1112]: Device devolo.model.Shutter is not supported (yet). Open an issue on github and ask for adding it.
Sep 11 21:22:41 homebridge[1112]: Device devolo.model.Unknown:Device is not supported (yet). Open an issue on github and ask for adding it.
Sep 11 21:22:41 homebridge[1112]: Device devolo.model.Unknown:Device is not supported (yet). Open an issue on github and ask for adding it.
Sep 11 21:22:48 homebridge[1112]: [9/11/2017, 9:22:48 PM] [Devolo] Initializing platform accessory 'Devolo Central Unit'...
...
Sep 11 21:22:48 homebridge[1112]: Scan this code with your HomeKit App on your iOS device to pair with Homebridge:
Sep 11 21:22:48 homebridge[1112]: ┌────────────┐
Sep 11 21:22:48 homebridge[1112]: │ 012-34-567 │
Sep 11 21:22:48 homebridge[1112]: └────────────┘
Sep 11 21:22:48 homebridge[1112]: (node:1112) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 message listeners added. Use emitter.setMaxListeners() to increase limit
Sep 11 21:22:48 homebridge[1112]: [9/11/2017, 9:22:48 PM] Homebridge is running on port 51826.
Sep 11 21:23:51 homebridge[1112]: COULDNT FIND SENSOR: devolo.Meter:hdm:ZWave:D8F7DDE2/6
Sep 11 21:23:51 homebridge[1112]: COULDNT FIND SENSOR: devolo.Meter:hdm:ZWave:D8F7DDE2/6
Sep 11 21:23:51 homebridge[1112]: [9/11/2017, 9:23:51 PM] [Devolo] HBDevoloSwitchMeterDevice (hdm:ZWave:D8F7DDE2/6) > CurrentConsumption > 11
Sep 11 21:23:51 homebridge[1112]: COULDNT FIND SENSOR: devolo.Meter:hdm:ZWave:D8F7DDE2/6
Sep 11 21:23:51 homebridge[1112]: COULDNT FIND SENSOR: devolo.Meter:hdm:ZWave:D8F7DDE2/6
Sep 11 21:23:51 homebridge[1112]: COULDNT FIND SENSOR: devolo.Meter:hdm:ZWave:D8F7DDE2/6
Sep 11 21:23:51 homebridge[1112]: COULDNT FIND SENSOR: devolo.Meter:hdm:ZWave:D8F7DDE2/6
Sep 11 21:23:51 homebridge[1112]: COULDNT FIND SENSOR: devolo.Meter:hdm:ZWave:D8F7DDE2/6
Sep 11 21:23:51 homebridge[1112]: COULDNT FIND SENSOR: devolo.Meter:hdm:ZWave:D8F7DDE2/6
Sep 11 21:23:51 homebridge[1112]: COULDNT FIND SENSOR: devolo.Meter:hdm:ZWave:D8F7DDE2/6
Sep 11 21:23:51 homebridge[1112]: COULDNT FIND SENSOR: devolo.Meter:hdm:ZWave:D8F7DDE2/6
Sep 11 21:23:51 homebridge[1112]: COULDNT FIND SENSOR: devolo.Meter:hdm:ZWave:D8F7DDE2/6
Sep 11 21:23:51 homebridge[1112]: COULDNT FIND SENSOR: devolo.Meter:hdm:ZWave:D8F7DDE2/6
Sep 11 21:23:51 homebridge[1112]: COULDNT FIND SENSOR: devolo.Meter:hdm:ZWave:D8F7DDE2/6
Sep 11 21:23:51 homebridge[1112]: COULDNT FIND SENSOR: devolo.Meter:hdm:ZWave:D8F7DDE2/6
Sep 11 21:23:51 homebridge[1112]: COULDNT FIND RULE PROPERTY: currentValue
Sep 11 21:23:51 homebridge[1112]: /usr/lib/node_modules/homebridge-devolo/node_modules/node-devolo/dist/DevoloDevice.js:134
Sep 11 21:23:51 homebridge[1112]: throw new Error('Device has no suitable sensor.');
Sep 11 21:23:51 homebridge[1112]: ^
Sep 11 21:23:51 homebridge[1112]: Error: Device has no suitable sensor.
Sep 11 21:23:51 homebridge[1112]: at SwitchMeterDevice.Device.getState (/usr/lib/node_modules/homebridge-devolo/node_modules/node-devolo/dist/DevoloDevice.js:134:23)
Sep 11 21:23:51 homebridge[1112]: at HBDevoloSwitchMeterDevice.getSwitchState (/usr/lib/node_modules/homebridge-devolo/dist/devices/HBDevoloSwitchMeterDevice.js:62:44)
Sep 11 21:23:51 homebridge[1112]: at emitThree (events.js:116:13)
Sep 11 21:23:51 homebridge[1112]: at Characteristic.On.emit (events.js:197:7)
Sep 11 21:23:51 homebridge[1112]: at Characteristic.On.Characteristic.getValue (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Characteristic.js:142:10)
Sep 11 21:23:51 homebridge[1112]: at Bridge.<anonymous> (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:706:20)
Sep 11 21:23:51 homebridge[1112]: at Array.forEach (native)
Sep 11 21:23:51 homebridge[1112]: at Bridge.Accessory._handleGetCharacteristics (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:670:8)
Sep 11 21:23:51 homebridge[1112]: at emitMany (events.js:127:13)
Sep 11 21:23:51 homebridge[1112]: at HAPServer.emit (events.js:204:7)
Sep 11 21:23:51 systemd[1]: homebridge.service: main process exited, code=exited, status=1/FAILURE
Sep 11 21:23:51 systemd[1]: Unit homebridge.service entered failed state.

**Comment by KiboOst** [comment]
For info, the D8F7DDE2/6 device causing problem is a wall plug Devolo V1 just like others:

```
{
    "name": "Prise Salon 1",
    "uid": "hdm:ZWave:D8F7DDE2/5",
    "sensors": "[\"devolo.Meter:hdm:ZWave:D8F7DDE2/5\",\"devolo.BinarySwitch:hdm:ZWave:D8F7DDE2/5\"]",
    "zoneId": "hz_2",
    "statUID": "st.hdm:ZWave:D8F7DDE2/5",
    "batteryLevel": -1,
    "model": "devolo.model.Wall:Plug:Switch:and:Meter",
    "icon": "light-bulb"
},
{
    "name": "Prise Salon 2",
    "uid": "hdm:ZWave:D8F7DDE2/6",
    "sensors": "[\"devolo.Meter:hdm:ZWave:D8F7DDE2/6\",\"devolo.BinarySwitch:hdm:ZWave:D8F7DDE2/6\"]",
    "zoneId": "hz_2",
    "statUID": "st.hdm:ZWave:D8F7DDE2/6",
    "batteryLevel": -1,
    "model": "devolo.model.Wall:Plug:Switch:and:Meter",
    "icon": "icon_19"
}
```

**Comment by KiboOst** [comment]
Here are two complete debug json from php API with full element, settings etc
Like you can see, both wall plugs are identical in sensors, elements and settings. But D8F7DDE2/6 cause homebridge-devolo to crash...

[debug.zip](https://github.com/kdietrich/homebridge-devolo/files/1295573/debug.zip)

**Comment by KiboOst** [comment]
Let us know if you need anything to help getting it working

**Comment by KiboOst** [comment]
Tried to reset accessories and persist caches, delete entire home from smarthome, restarted all.
Exact same problem
(node:1024) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 message listeners added. Use emitter.setMaxListeners() to increase limit

 /usr/lib/node_modules/homebridge-devolo/node_modules/node-devolo/dist/DevoloDevice.js:134
Sep 24 10:45:54 raspberrypi homebridge[1024]: throw new Error('Device has no suitable sensor.');
Sep 24 10:45:54 raspberrypi homebridge[1024]: ^
Sep 24 10:45:54 raspberrypi homebridge[1024]: Error: Device has no suitable sensor.
Sep 24 10:45:54 raspberrypi homebridge[1024]: at SwitchMeterDevice.Device.getState (/usr/lib/node_modules/homebridge-devolo/node_modules/node-devolo/dist/DevoloDevice.js:134:23)
Sep 24 10:45:54 raspberrypi homebridge[1024]: at HBDevoloSwitchMeterDevice.getSwitchState (/usr/lib/node_modules/homebridge-devolo/dist/devices/HBDevoloSwitchMeterDevice.js:62:44)
Sep 24 10:45:54 raspberrypi homebridge[1024]: at emitThree (events.js:116:13)
Sep 24 10:45:54 raspberrypi homebridge[1024]: at Characteristic.On.emit (events.js:197:7)
Sep 24 10:45:54 raspberrypi homebridge[1024]: at Characteristic.On.Characteristic.getValue (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Characteristic.js:142:10)
Sep 24 10:45:54 raspberrypi homebridge[1024]: at Bridge.<anonymous> (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:706:20)
Sep 24 10:45:54 raspberrypi homebridge[1024]: at Array.forEach (native)
Sep 24 10:45:54 raspberrypi homebridge[1024]: at Bridge.Accessory._handleGetCharacteristics (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:670:8)
Sep 24 10:45:54 raspberrypi homebridge[1024]: at emitMany (events.js:127:13)
Sep 24 10:45:54 raspberrypi homebridge[1024]: at HAPServer.emit (events.js:204:7)

Let us know if you fix it

**Comment by kdietrich** [comment]
Is it possible that you send me your ssh credentials once again via mail? Guess it's easier to track the error that way.

**Comment by KiboOst** [comment]
Sure, will see this afternoon as it is turned off right now.
Thanks

**Comment by KiboOst** [comment]
email sent ;-)

**Comment by KiboOst** [comment]
Not sure about this but regarding:
MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 message listeners added. Use emitter.setMaxListeners()

See this: https://nodejs.org/docs/latest/api/events.html#events_emitter_setmaxlisteners_n

Not sure, but this could cause the no sensor found ?

**Comment by KiboOst** [comment]
Last 0.1.5 is running fine !
Many thanks Kevin for your time fixing it :-)
