### ISSUE TITLE
Timeout / Heartbeat als Variable

### ISSUE THREAD

**Issue by nicoh88** [kdietrich/homebridge-devolo#2]
Es wäre gut, wenn man den Timeout bzw. Heartbeat, welcher aktuell fest auf 3 steht, in der config.json anpassen könnte.

**Comment by kdietrich** [comment]
Fixed in the next release with https://github.com/kdietrich/homebridge-devolo/commit/36482c271c9b2513dd441f19b591c8b3818ac2ec.
