### ISSUE TITLE
MaxListenersExceededWarning

### ISSUE THREAD

**Issue by kdietrich** [kdietrich/homebridge-devolo#20]
`Sep 26 14:07:31 raspberrypi homebridge[18380]: (node:18380) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 message listeners added. Use emitter.setMaxListeners() to increase limit`

**Comment by KiboOst** [comment]
Like I said by email, to fix this issue:

Edit node-devolo/dist/DevoloMisc.js
and add:
require('events').EventEmitter.defaultMaxListeners = 100;

after:
var events_1 = require("events");

So:
```
"use strict";
var DevoloApi_1 = require("./DevoloApi");
var events_1 = require("events");
require('events').EventEmitter.defaultMaxListeners = 100;
var Zone = (function () {
   ....
```

**Comment by kdietrich** [comment]
Thank you! 👍
