### ISSUE TITLE
Error: connect ECONNREFUSED 192.168.xx.xx:80

### ISSUE THREAD

**Issue by ramsnerm** [kdietrich/homebridge-devolo#22]
I don't no why or when but if start the devolo plugin I always get the message
`[Devolo] HBDevoloPlatform > Error: connect ECONNREFUSED 192.168.xx.xx:80`

If I ping the DHC or use the php-devoloAPI I get a proper reaction. Login credentials as well as the uuid, .. are correct.

Any ideas what I could do/look/check?

**Comment by kdietrich** [comment]
Which version of `homebridge-devolo` are you using? Can you start homebridge with ´homebridge -D` and send me the complete log output?

**Comment by ramsnerm** [comment]
Currently I am using latest ```homebridge-devolo``` version `v0.1.5'.
Here is a complete log file: [logfile.txt](https://github.com/kdietrich/homebridge-devolo/files/1346654/logfile.txt)

#### Precondition
The Homebridge must be run for some hours to show this effect. Otherwise a restart works as expected.

#### Failure picture:
* Homebridge is starting, ever model is loaded
* Initialization of all other modules are happening
* In between 
```
[2017-9-30 19:43:14] Loaded plugin: homebridge-devolo
[2017-9-30 19:43:14] Registering platform 'homebridge-devolo.Devolo'
[2017-9-30 19:43:30] [Devolo] Initializing Devolo platform...
[2017-9-30 19:43:30] [Devolo] HBDevoloPlatform > Initializing (Version: 201702221607)
[2017-9-30 19:43:30] [Devolo] HBDevoloPlatform > Configuration:
{ platform: 'Devolo',
  name: 'Devolo',
  host: '192.168.1.48',
  email: 'xxx',
  password: 'xxx',
  uuid: 'xxx',
  gateway: 'xxx',
  passkey: 'xxx',
  heartrate: 3 }
[2017-9-30 19:43:30] [Devolo] HBDevoloPlatform > Searching for Devolo Central Unit.
[2017-9-30 19:43:31] [Devolo] HBDevoloPlatform > Error: connect ECONNREFUSED 1xx.xx.x.xx:80
```

At this point everything seems to run, except Devolo, Additional the Homebridge is not coming to the "registration" screen so it is not active and not communicating with HomeKit.

#### Workaround at the moment: 
* Disconnect the Deveolo Home Control from power Device and reconnect it appr. 2 minutes
* Restart the Homebridge service
* Connect works again even if I restart the device

#### Interresting Observation - May be a hint for the problem ...
Only when the connect runs without the error following messages are also shown in the log:
```
Trying to connect to socket.
Websocket open 
```

**Comment by nicoh88** [comment]
Hi @ramsnerm,

does the problem still occur or can we close this issue?
If you do not report within the next 5 days, we would close the issue.

Regards Nico

**Comment by 00kai** [comment]
Hi,
i have the same problem like @ramsnerm and the workaround works until the Devolo Home Control shut down next.

But maybe someone can fix this problem!
Any idea?

Many thanks!

**Comment by nicoh88** [comment]
@ramsnerm @00kai 

**Neuigkeiten zu diesem Thema?**

Bei mir lässt sich das Problem mit 2 Minuten stromlos machen und `homebridge` Neustart leider nicht lösen.
