### ISSUE TITLE
Wish: Support Qubino and Bush& Jäger Device

### ISSUE THREAD

**Issue by ramsnerm** [kdietrich/homebridge-devolo#24]
I have seen you integrate now the quoin shutter device. So maybe next you could consider to add the standard qubino flush 1/1D relay. Thanks

**Comment by KiboOst** [comment]
I have just ordered a Qubino 1 relay ZMNHAD1
Once received and installed, I will generate a debug report with the API ;-)

**Comment by kdietrich** [comment]
@KiboOst Great news! 👍

**Comment by KiboOst** [comment]
@ramsnerm You can test by replacing the files in the zip.
This actually works (running here) giving first Q1 contact in HomeKit for Qubino 2 relay.
It should works with qubino 1 relay

@kdietrich I have name de device HBGenericSwitchDevice as this could work for 1relay, 1Drelay, 2relay and maybe fibaro relays, dunno. Do whatever you think is best ;-)

maslisteneremitter error is also fixed
[homebridge-devolo.zip](https://github.com/kdietrich/homebridge-devolo/files/1346336/homebridge-devolo.zip)

More info when 1relay get home ;-)

**Comment by ramsnerm** [comment]
So I think you are looking for that:

**Comment by ramsnerm** [comment]
@kdietrich: I tested your fork and yes I can confirm contact 1 of the Qubino Flush 2 relay is shown. Also I get no longer the message: Open an issue on github and ask for adding it, but ...

unfortunately the other two relays Qubino Flush 1D relay and the  Busch & Jäger Switch are not showing up in HomeKit.

**Comment by KiboOst** [comment]
Yes, this is normal as these report unknown, and I check for devices having more than one switch.
Will see if Kevin provide support, or I can modify something so it get all unknown device that have a switch inside.

**Comment by KiboOst** [comment]
In Devolo.js line 178 change
if (el.indexOf('devolo.BinarySwitch:hdm:ZWave') > -1 && el.endsWith('#1')) {
to
if (el.indexOf('devolo.BinarySwitch:hdm:ZWave') > -1 ) {

it should create one switch for every unknown device that have a switch inside

**Comment by ramsnerm** [comment]
@KiboOst: Thanks for the tip. I had to change the line a bit to be able to see the 2 relay **and** the 1 relay in HomeKit. Without that I only saw the 1 relay and the Busch & Jäger switch:

```if ((el.indexOf('devolo.BinarySwitch:hdm:ZWave') > -1 && el.endsWith('#1')) || (el.indexOf('devolo.BinarySwitch:hdm:ZWave') > -1 )) {```

**Comment by KiboOst** [comment]
Nice ;-)

I didn't forked the repo just for this, hope @kdietrich will have a look. This approach allow supporting nearly every switch, but is a bit trivial ;-) Anyway it is a filter after all known devices so it won't interfere with known/supported one.

As Qubino shutter are recognized as official Devolo shutter, I guess it should be the same for 1 Relay recognized as Relay. Will let you know once I got it.

**Comment by KiboOst** [comment]
@kdietrich 
Qubino 1relay is arrived !!
Like I though: "deviceModelUID": "devolo.model.Relay"
Good news is that switching wall switch get the device updated in DHC, and consumption report also!
Is noted offline anyway, like qubino shutters. This will be fixed in future Devolo updates and don't prevent them to work perfectly !!

[Qubino1Relay_ZMNHAD1.zip](https://github.com/kdietrich/homebridge-devolo/files/1356070/Qubino1Relay_ZMNHAD1.zip)

**Comment by KiboOst** [comment]
And works perfectly in homebridge-devolo

`
else if (item.properties.deviceModelUID.indexOf('Relay') > -1) {
    device = new DevoloDevice_1.GenericSwitchDevice();
 }`

YIIHAAAAA !!!

**Comment by ramsnerm** [comment]
Can confirm!

**Comment by kdietrich** [comment]
Hey guys, a quick update on this: @KiboOst is going to send me his Flush 2 Relay for integration. I will wait for it to arrive because I want to integrate Flush 1-, Flush 2-, Flush whatever-Relay into ONE generic device. There needs some API refactoring to be done but I think this is cleverest way to go.

**Comment by nicoh88** [comment]
For Busch-Jaeger this [Issue](https://github.com/kdietrich/homebridge-devolo/issues/14).
For Qubino Flush 1 and Flush 2 this [Issue](https://github.com/kdietrich/homebridge-devolo/issues/21).
