### ISSUE TITLE
Support of Door Sensor / Window Contact

### ISSUE THREAD

**Issue by baronScout** [kdietrich/homebridge-devolo#25]
Hello,
I have connected a Smart Metering Plug and a Door Sensor to my Devolo Central Unit.
Homebridge recognizes the Plug and I can switch it on and of in the Home app but no further information are shown.
The door Sensor is not supported.
The logfile is attached.
It would be great if you can help me.
[logfile.txt](https://github.com/kdietrich/homebridge-devolo/files/1380754/logfile.txt)

**Comment by KiboOst** [comment]
Is it a Devolo door sensor ? These are recognized and works fine in HomeKit here

**Comment by baronScout** [comment]
I reseted all my devices and now it works just fine. Thank you
