### ISSUE TITLE
Homebridge Devolo - Figaro devices

### ISSUE THREAD

**Issue by JH1000** [kdietrich/homebridge-devolo#26]
Fibaro z-wave devices, controlled by devolo central unit, are not supported. Is there a solution for this?
Error message: "Device devolo.model.Unknown:Device is not supported"

Thank you

**Comment by kdietrich** [comment]
Hi JH1000, which Fibaro device are you trying to control?

**Comment by kdietrich** [comment]
@JH1000 Could you please update to the latest version and run the steps described here: https://github.com/kdietrich/homebridge-devolo#support-of-new-devices Afterwards please upload the created file in this issue. This should help me integrate new devices.
