### ISSUE TITLE
Support for Danfoss LC-13

### ISSUE THREAD

**Issue by topa** [kdietrich/homebridge-devolo#27]
The Danfoss LC-13 thermostat valve should be identical to the one provided be devolo. I guess to add support for the Danfoss devices should be very easy if we find out the name which is reported.

I have a couple of those devices. What is the easiest way to get that information?

**Comment by lemisoft** [comment]
I'm using the LC-13 too (5 original Devolo and 5 Danfoss). It would be great to have support of them!

**Comment by kdietrich** [comment]
Hi topa, easiest way to find out (if you know JS) would be to use this node.js API: https://github.com/kdietrich/node-devolo. However I'm planning to create a short snippet of code that outputs the relevant info for an integration.

**Comment by kdietrich** [comment]
@topa @lemisoft Could you please update to the latest version and run the steps described here: https://github.com/kdietrich/homebridge-devolo#support-of-new-devices Afterwards please upload the created file in this issue. This should help me integrate new devices.

**Comment by lemisoft** [comment]
Hallo,

ich versuche am Wochenende den update zu machen...

Viele Grüße,
Andreas


-- 
lemisoft • Andreas Lehmann
Nymphenburger Str. 147 • 80634 München • Germany
Tel: +49-89-14729332 • Mobile: +49-172-8569069
Fax: +49-89-14729334 • http://www.lemisoft.de
Skype: lemisoft • Twitter: @lemisoft

**Comment by topa** [comment]
Hi! 👋 

I finally found some time and created the log file as described in the link @kdietrich has posted, however it seems like there aren't any relevant information (I've removed potentially security relevant details.

[debugoutput.log](https://github.com/kdietrich/homebridge-devolo/files/2105366/debugoutput.log)

```shell
Device unk.model.Unknown:Device is not supported (yet). Open an issue on github and ask for adding it.
Device unk.model.Unknown:Device is not supported (yet). Open an issue on github and ask for adding it.
Device unk.model.Unknown:Device is not supported (yet). Open an issue on github and ask for adding it.
Device unk.model.Unknown:Device is not supported (yet). Open an issue on github and ask for adding it.
Device unk.model.Unknown:Device is not supported (yet). Open an issue on github and ask for adding it.
Device unk.model.Unknown:Device is not supported (yet). Open an issue on github and ask for adding it.
```

Seems not be very helpful though.

**Comment by topa** [comment]
Alright, I debugged a little bit and `console.log`ed in `Devolo.js` the `items`.

So a LC-13 valve thermostaste object looks like that:

```json
    {
        "UID": "hdm:ZWave:E6F94271/15",
        "properties": {
            "pendingOperations": null,
            "batteryLow": false,
            "zoneId": "hz_1",
            "isSecurelyIncluded": false,
            "zone": "Arbeitszimmer",
            "prodTypeID": "0x0005",
            "statisticsUID": "st.hdm:ZWave:E6F94271/15",
            "secureInclusionCode": 0,
            "prodID": "0x0004",
            "status": 2,
            "settingUIDs": [
                "gds.hdm:ZWave:E6F94271/15"
            ],
            "manID": "0x0002",
            "batteryLevel": 73,
            "icon": "icon_1",
            "operationStatus": null,
            "description": null,
            "wrongDevicePaired": false,
            "isOwn": true,
            "deviceModelUID": "unk.model.Unknown:Device",
            "itemName": "Not of interest,
            "elementUIDs": [
                "devolo.MultiLevelSwitch:hdm:ZWave:E6F94271/15"
            ]
        },
```

**Comment by nicoh88** [comment]
Support with v0.1.9 

`npm update -g --unsafe-perm homebridge-devolo`

**Comment by topa** [comment]
It seems like version 0.1.11 does not support these Danfoss valves anymore, at least (my) homebridge does not recognize them anymore.
If I start homebridge in debugging mode I get the following output:

![img_78a0babc5ef2-1](https://user-images.githubusercontent.com/1116484/46720316-808e1a00-cc70-11e8-9f77-983103cdfd13.jpeg)

Could you confirm that this is actually a bug or do you think something is wrong on my side?

**Comment by nicoh88** [comment]
Sorry, my fault - please use the newest version 0.1.12.

`npm install -g --unsafe-perm homebridge-devolo@latest`

What is this iOS app?

**Comment by topa** [comment]
> What is this iOS app?

The App is just called [homebridge](https://itunes.apple.com/de/app/homebridge-für-raspberrypi/id1123183713?mt=8
).

You can basically configure homebridge on your raspberry pi in a very convenient way.

**Comment by simplenotezy** [comment]
Hi! I am curious; is HomeBridge supporting connecting to Danfoss Eco 2 Thermostats now?
