### ISSUE TITLE
Regeln und Szenen

### ISSUE THREAD

**Issue by Arakansas** [kdietrich/homebridge-devolo#29]
Hallo, 

gibt es eine Möglichkeit dieRegeln und Szenen von DEVOLO zu importieren

Gruß
 Arakansas

**Comment by kdietrich** [comment]
Hallo Arakansas,

mit Hilfe der Option `sceneWhitelist` kannst du Szenen nach Home exportieren. Diese erscheinen als Taster und können per Tap geschalten werden. Mit der Option `ruleWhitelist` kannst du Regeln nach Home exportieren. Diese werden ebenfalls als Taster angezeigt. Ist die Regel deaktiviert, ist der Taster deaktiviert und umgekehrt. Aufgrund von Apples Restriktionen ist es jedoch nicht möglich Devolo Regeln zu Homekit Regeln zu konvertieren.

**Comment by Arakansas** [comment]
erkläre bitte mal einem blutigen Anfänger wo ich die Option wie eingeben muß.

Danke für deine Geduld

Gruß
Andreas

**Comment by nicoh88** [comment]
Beispiel:

```
{
        "platform": "Devolo",
        "name": "Devolo",
        "host": "192.168.XXX.XX",
        "email": "xxx@xxx.com",
        "password": "xxx",
        "heartrate": 3,
        "uuid": "XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX",
        "gateway": "XXXXXXXXXXXXX",
        "passkey": "XXXXXXXXXXXXX XXXXXXXXXXXXX",
        "ruleWhitelist": ["Alarmanlage"],
        "sceneWhitelist": ["Alarmanlage aktivieren", "Alarmanlage deaktivieren"],
        "deviceBlacklist": ["W Sternlampe", "W Herrnhuter Sterne", "W Winterwald", "W Tannenbaum"],
	"deviceDebugging": false
    },
```
