### ISSUE TITLE
Messsteckdose - remoteSwitch / targetRemoteSwitch

### ISSUE THREAD

**Issue by nicoh88** [kdietrich/homebridge-devolo#3]
Hallo,

wenn man über das Devolo Webinterface, dass schalten einer Messsteckdose deaktiviert, sollte dies auch nicht in HomeKit schaltbar sein.

Daher bitte "_remoteSwitch_" bzw. "_targetRemoteSwitch_" beachten.

`{
    "result": {
        "items": [{
            "UID": "ps.hdm:ZWave:XXXXXXXX/XX",
            "properties": {
                "pendingOperations": null,
                "operationStatus": null,
                "remoteSwitch": false,
                "targetRemoteSwitch": false,
                "targetLocalSwitch": false,
                "itemId": null,
                "localSwitch": false
            },
            "attributes": {},
            "objectClass": ["com.devolo.fi.setting.ProtectionSetting", "com.devolo.fi.widget.DeviceSetting", "com.devolo.fi.async.base.AsyncFunctionalItem", "com.prosyst.mbs.services.fim.FunctionalItem"],
            "tags": []
        }]
    },
    "jsonrpc": "2.0"
}`

**Comment by kdietrich** [comment]
Fixed in the next release with https://github.com/kdietrich/homebridge-devolo/commit/c350be52dd1b78e072d77d91f29161375e269066.
