### ISSUE TITLE
Sensationell...!!!

### ISSUE THREAD

**Issue by eyk2000** [kdietrich/homebridge-devolo#32]
Hallo und Herzlichen Dank für diese Arbeit - Weltklasse!
Endlich kann ich über Siri (fast vollständig) meine Devolo HomeControl "ansprechen".

Ist die Unterstützung für Qubino Flush Unterputzmodule geplant...?
Davon habe ich einige im Haus verbaut und die laufen sehr gut mit der Devolo HC zusammen.

Herzliche Grüße 

Eyk

**Comment by kdietrich** [comment]
Hallo @eyk2000, danke für dein Lob! Ja, eine Unterstützung des Qubino Flush Relay ist fest geplant. Hier gibt es dafür schon ein Issue: https://github.com/kdietrich/homebridge-devolo/issues/21. Leider bin ich bisher noch nicht zur Umsetzung gekommen, da die originalen Devolo-Komponenten vorrangig implementiert werden. Danach steht das Flush Relay aber ganz oben auf der Liste. Ich schließe das Issue hier mal, damit keine doppelten offen sind.
