### ISSUE TITLE
Aeotec Sirene ZW080-BI und Fibaro Relais FGS-222

### ISSUE THREAD

**Issue by Arakansas** [kdietrich/homebridge-devolo#33]
Hallo, 

das hat ja super geklappt. DANKE

wenn Du jetzt noch die Sirene und die Relais zum laufen bringst bin ich überglücklich.

Aeotec Sirene ZW080-BI - Z-Wave Plus

Fibaro Relais Unterputzeinsatz 1 Schalter 2,5kW - Z-Wave, 1 Stück, FIBEFGS-213

wie gewünscht die log-Datei

DANKE

Gruß
Andreas
[debugoutput.log](https://github.com/kdietrich/homebridge-devolo/files/1777608/debugoutput.log)

**Comment by nicoh88** [comment]
Hi Andreas,

du hast offensichtlich vergessen `deviceDebugging` in deiner `config.json` auf `true` zusetzen.
[Hier](https://github.com/kdietrich/homebridge-devolo/issues/28#issuecomment-368999043) ausführlich erklärt.

Bitte nochmal probieren.
Danke 🙏🏼

**Comment by Arakansas** [comment]
Wer lesen kann ist klar im Vorteil……………….

habe die lag -Datei angehängt 



DANKE

Gruß
Andreas

**Comment by nicoh88** [comment]
@Arakansas 

Jetzt hast du die Logdatei vergessen anzuhängen. :-/

**Comment by Arakansas** [comment]
ich glaub ich werde zu alt für solch ein Mist…………..




Gruß
Andreas

**Comment by Arakansas** [comment]
so nun noch mal ...
[debugoutput.log](https://github.com/kdietrich/homebridge-devolo/files/1799148/debugoutput.log)

**Comment by nicoh88** [comment]
@Arakansas Wie heißen die Geräte in deinem Devolo Home Control?

Gruß Nico

**Comment by Arakansas** [comment]
die Sirene heist einfach Sirene
und die Relais einfach Relai1, Relai2 und Relai3

**Comment by nicoh88** [comment]
@Arakansas 

Ein Relais für die Integration befindet sich aktuell auf den Versandweg - die Integration sollte bis Ende nächster Woche erfolgt sein. Melde mich.

Sirenen werden von Apple HomeKit noch nicht Funktional unterstützt.

Wir können die Aeotec Sirene aber genauso integrieren wie die von Devolo - dann kann man nur die vier Stati vom "Sicherheitssystem" setzen und ggf. über eine Regel / Automation, am Besten über [Controller für HomeKit](https://itunes.apple.com/de/app/controller-für-homekit/id1198176727?mt=8) erstellen, etwas in Devolo ausführen / aktivieren.

Ok?

**Comment by Arakansas** [comment]
OK - Danke

Von meinem iPhone gesendet

**Comment by nicoh88** [comment]
@Arakansas Bist du dir sicher, dass es "FGS-213" sind? Und nicht "FGS-212"?

**Comment by nicoh88** [comment]
@Arakansas Die Aussage reicht mir leider nicht.

Die 3 Geräte "Relai1", "Relai2" und "Relai3" haben die gleiche prodID und prodTypeID - d.h. die 3 Geräte sollten baugleich sein. Ich möchte jetzt gerne von dir wissen, welche Fibaro Gerätebezeichnung auf dem Gehäuse steht. Die Frage ist ob FGS-212, FGS-213, FGS-222 oder FGS-223?

Solltest du noch andere Fiabro Geräte als "Relai1", "Relai2" und "Relai3" haben, musste du mir den genauen Gerätetypen und Gerätenamen noch mitteilen.

Gruß Nico

**Comment by Arakansas** [comment]
Es sin die FGS-222

Von meinem iPhone gesendet

**Comment by nicoh88** [comment]
Hi @kasek1975,

ich habe homebridge-devolo aktualisiert und es werden jetzt die Fibaro FGS-212, FGS-213, FGS-222, FGS-223 und die Aeotec Sirene ZW080-BI unterstützt.

Mit dem Befehl, eventuell noch ein `sudo` davor ...

`npm install kdietrich/homebridge-devolo#master -g --unsafe-perm`

... aktualisierst du auf die aktuelle GitHub Version.

Den Output, wenn ein Gerät nicht unterstützt wird, habe ich auch erweitert - alle nötigen Infos um eine schnelle Integration zu gewährleisten.

> Device > NAME-IM-DEVOLO < is not supported (yet) or devolo has something changed. Open an issue on github and ask for adding it.
> > Model: devolo.model.Unknown:Device
> > ProductID: 0x0000
> > ProductTypeID: 0x1000
> > Sensors: devolo.BinarySwitch:hdm:ZWave

Würde mich über Feedback freuen. 👍

**Comment by nicoh88** [comment]
Und? 😅

**Comment by Arakansas** [comment]
Werde ich testen sobald ich wieder zuhause bin. So in 14 Tagen 😎


Von meinem iPhone gesendet

**Comment by nicoh88** [comment]
@Arakansas 

Alles klar. 
Es wird sicher gehen, daher schließe ich das Issue. 👍 
Ansonsten meldest du dich einfach nochmal. 😄

**Comment by Arakansas** [comment]
OK - Danke für deine Bemühungen 

Super Job !!!🤗

Von meinem iPad gesendet
