### ISSUE TITLE
Version 0.1.8

### ISSUE THREAD

**Issue by Tomaso12** [kdietrich/homebridge-devolo#35]
Servus.

Erstmal vielen dank für dieses tolle Plugin. Ich nutze es mittlerweile seit längerem und bin total begeistert. 
Gestern habe ich das neue update entdeckt und natürlich sofort versucht es zu installieren. Leider ist dabei etwas schief gegangen und nun funktioniert nichts mehr.

Ich habe das Plugin deinstalliert und vergeblich versucht es wieder zu installieren.

pi@raspberrypi:~ $ npm install -g homebridge-devolo
Unhandled rejection Error: ENOSPC: no space left on device, writeef8ae15baca997

┌──────────────────────────────────────────────────────┐
│               npm update check failed                │
│         Try running with sudo or get access          │
│         to the local update config store via         │
│ sudo chown -R $USER:$(id -gn $USER) /home/pi/.config │
└──────────────────────────────────────────────────────┘
npm ERR! cb() never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

Diese Meldung wird angezeigt. 

Sorry bin totaler Anfänger, aber vielleicht könnt ihr mir hiermit helfen.

**Comment by kdietrich** [comment]
Hallo,

das klingt als wäre nicht genug Speicher frei, was ich bezweifle? Führe mal vor dem Installieren `npm cache clear` aus und probiere es dann noch mal.

**Comment by Tomaso12** [comment]
Vielen dank für die Antwort.
Aus lauter Verzweiflung habe ich aber mittlerweile den kompletten Pi und die Homebridge neu aufgesetzt.
Jetzt geht auch alles wieder. Gott sei Dank.
Trotzdem danke und Kompliment für dieses tolle Plugin...
