### ISSUE TITLE
Keine Verbindung zur Home Control Zentrale

### ISSUE THREAD

**Issue by AndreH1978** [kdietrich/homebridge-devolo#37]
Hallo, 
bin hier neu.
Habe alles rund um das Devolo Plugin hier gelesen und verfolgt. 
Finde die Idee Hammer!
Habe alles installiert, leider ein Problem das Homebridge die Zentrale anscheinend nicht findet. Wer kann mir helfen?

**Comment by AndreH1978** [comment]
{
  "accessories" : [

  ],
  "bridge" : {
    "username" : "CD:22:3D:E3:CE:94",
    "name" : "Homebridge",
    "pin" : "031-45-494",
    "port" : 51826
  },
  "platforms" : [
    {
      "email" : "email",
      "password" : "Pass",
      "host" : "192.168.178.22",
      "name" : "Devolo",
      "platform" : "Devolo"
    }
  ]
}

**Comment by AndreH1978** [comment]
kann mir keiner einen Tip geben?
Das hier erscheint ..

[2018-6-12 10:28:10] Loading 1 platforms...
[2018-6-12 10:28:10] [Devolo] Initializing Devolo platform...
[2018-6-12 10:28:10] [Devolo] HBDevoloPlatform > Searching for Devolo Central Unit.
[2018-6-12 10:28:10] Loading 1 accessories...
[2018-6-12 10:28:10] [Sonos - Büro] Initializing Sonos accessory...
[2018-6-12 10:28:11] [Sonos - Büro] Found a playable coordinator device at 192.168.178.23 in zone 'Büro' for accessory 'Sonos - Büro' in accessory room 'Büro'

**Comment by nicoh88** [comment]
@AndreH1978: Konntest du dein Problem bereits lösen?

**Comment by AndreH1978** [comment]
Hi. Nein. Leider noch nicht

Mit freundlichen Grüßen

Hofbeck Andre

Privat:
St. Michaelstraße 12
91336 Heroldsbach

Mobil: 0173-5717088
Telefon: 09190 9945923
Fax: 09190-9945875

andre.hofbeck@googlemail.com

**Comment by nicoh88** [comment]
Hi Andre,

bist du dir sicher, dass die `192.168.178.22` deine Devolo Zentrale ist? Ein Netzwerk-Scan wäre cool. 😄

**Comment by AndreH1978** [comment]
Sorry, ich kann immer erst im Büro tätig werden. 
Da hier die komplette Smart-Home -Geschichte installiert ist. Die Öffnungszeiten hier sind 09:00 bis 13 Uhr.. deswegen antworte ich immer Zeitversetzt. Ich hab 2 Devolo Geräte im Netzwerk..

**Comment by nicoh88** [comment]
Hi @AndreH1978,

konntest du das Problem lösen?

Bist du dir sicher, dass die `192.168.178.22` deine Devolo Zentrale ist?
Was meinst du mit 2 Devolo Geräten im Netzwerk? Zwei Zentralen oder zwei Smart Home Geräte?
Das Einzige war mir auffällt, ist die falsche Reihenfolge in deiner `config.json`...

```
    "platform" : "Devolo",
    "name" : "Devolo",
    "host" : "x.x.x.x",
    "email" : "mail@host.com",
    "password" : "topsecret123"
```

**Comment by AndreH1978** [comment]
Hi.. Hast Du den Screenshot gesehen? Ich würde stark behaupten dass das die IP ist. 
Mit 2 Geräten meine ich einmal den Powerline Adapter der angezeigt wird, zum anderen Devolo (also die Home Control).
Devolo Geräte sind hier sehr viele verbaut. Alles was es gibt denke ich, inklusive den Unterputz-Dimmern / Schaltern etc..
Ich bin hier langsam ratlos. 
Wenn es Dir irgendwie möglich ist mal kurz zu telefonieren, wäre total klasse. 
0173-5717088.
Wie gesagt.. Die Sachen sind hier im Büro eingebaut. Wäre toll wenn Du mich am Handy kontaktierst. 
Viele Grüße 

Andre

**Comment by nicoh88** [comment]
Hi Andre,

welche Screenshot? Es gibt keinen Screenshot hier im Issue.
Telefonieren geht leider nicht. 😢 

Gib mir SSH Zugriff auf das Homebridge-System, ich schaue es mir an. 🔮👍

**Comment by nicoh88** [comment]
Problem gelöst! Zwei Zentralen in myDevolo ist eine Besonderheit - für die Zukunft [hier](url
https://github.com/kdietrich/homebridge-devolo#multiple-central-units) festgehalten. 👍

**Comment by AndreH1978** [comment]
Hey…. Wahhhhhhhnsinn!! Wie kann ich mich bei Dir bedanken?
