### ISSUE TITLE
Fibaro Double Switch 2 FGS-223 ZW5

### ISSUE THREAD

**Issue by OliTheo** [kdietrich/homebridge-devolo#40]
I am using ioBroker ham and have add the homebridge-devolo to it. / however I have problems please see log:
needs to be read from bottom to top. 

am.0 | 2018-09-26 16:32:16.599 | warn | Exception: Error: Device has no suitable sensor.
-- | -- | -- | --
ham.0 | 2018-09-26 16:32:16.573 | info | cleaned everything up...
ham.0 | 2018-09-26 16:32:16.570 | error | at /opt/iobroker/node_modules/iobroker.ham/node_modules/homebridge-devolo/dist/index.js:71:17
ham.0 | 2018-09-26 16:32:16.570 | error | at /opt/iobroker/node_modules/iobroker.ham/node_modules/homebridge-plugin-wrapper/hap-nodejs/lib/util/once.js:16:19
ham.0 | 2018-09-26 16:32:16.570 | error | at Server.<anonymous>  (/opt/iobroker/node_modules/iobroker.ham/node_modules/homebridge-plugin-wrapper/homebridge/server.js:399:24)
ham.0 | 2018-09-26 16:32:16.570 | error | at WrapperBridge.addBridgedAccessory  (/opt/iobroker/node_modules/iobroker.ham/node_modules/homebridge-plugin-wrapper/index.js:138:17)
ham.0 | 2018-09-26 16:32:16.570 | error | at registerEventsForCharacteristic  (/opt/iobroker/node_modules/iobroker.ham/node_modules/homebridge-plugin-wrapper/index.js:128:28)
ham.0 | 2018-09-26 16:32:16.570 | error | at Characteristic.DevoloCurrentConsumption.Characteristic.getValue  (/opt/iobroker/node_modules/iobroker.ham/node_modules/homebridge-plugin-wrapper/hap-nodejs/lib/Characteristic.js:163:10)
ham.0 | 2018-09-26 16:32:16.570 | error | at Characteristic.DevoloCurrentConsumption.emit (events.js:217:7)
ham.0 | 2018-09-26 16:32:16.570 | error | at emitThree (events.js:136:13)
ham.0 | 2018-09-26 16:32:16.570 | error | at Array.HBQubinoRelay2Device.getDevoloCurrentConsumption  (/opt/iobroker/node_modules/iobroker.ham/node_modules/homebridge-devolo/dist/devices/HBQubinoRelay2Device.js:80:44)
ham.0 | 2018-09-26 16:32:16.570 | error | at Relay2Device.Device.getCurrentValue  (/opt/iobroker/node_modules/iobroker.ham/node_modules/node-devolo/dist/DevoloDevice.js:206:19)
ham.0 | 2018-09-26 16:32:16.570 | error | Error: Device has no suitable sensor.
ham.0 | 2018-09-26 16:32:16.569 | error | uncaught exception: Device has no suitable sensor.
ham.0 | 2018-09-26 16:32:16.501 | info | updateState Schalter-Küche.Schalter-Küche-2.Name: value =  /common=  {"type":"string","read":true,"write":false,"role":"text","name":"Name","unit":""}

any help would be great. Thanks OliTheo

**Comment by nicoh88** [comment]
Hi Oli,

deinem Gerätenamen entnehme ich, dass du Deutsch sprichst.
Die Fehlermeldung kommt, da homebridge-devolo keine Sensoren an deinem "Schalter-Küche" findet.

`Error: Device has no suitable sensor.`

Setze das Geräte doch bitte mal auf die Blacklist und versuche es erneut.
Danke

**Comment by OliTheo** [comment]
Hallo Nico,
vielen Dank für die Schnelle Antwort. Wie mache ich das mit der Blacklist? / das Gerät selbst ist ein Fibaro Double Switch 2 FGS-223 ZW5  welches mit Devolo Home Control Vernetzt ist. Ich nutze aber tatsächlich nur einen Schalter davon der zweite wird nicht genutzt.

Danke für die Hilfe
Gruss
Oli

**Comment by nicoh88** [comment]
Hi Oli,

du musst halt deine `config.json` um eine Zeile mit `deviceBlacklist` erweitern - siehe unten.

```
"passkey": "f17bb93aa318cfa7b12ff74a892a9262",
"deviceBlacklist": ["NAME-IM-DEVOLO"],
"deviceDebugging": false
```

Der Fibaro Double Switch wird noch nicht unterstützt- deswegen die Fehlermeldung. Habe mal einen bestellt, die Integration sollte bis Ende nächster Woche erledigt sein. 

Gruß

**Comment by OliTheo** [comment]
Komme nicht weiter:
hatte folgendes eingegeben:
{
  "description": "Add configuration for your accessories or platforms according to the docs of the plugins.",
  "accessories": [],
  "platforms": [
    {
      "password": "xxxxx",
      "platform": "Devolo",
      "uuid": "xxxxxxxxxxxx",
      "email": "absssss",
      "host": "x.x.x.x",
      "gateway": "1234567",
      "passkey": "abc1234567",
      "name": "Devolo",
      "deviceBlacklist": [
        "Schalter-Küche.Schalter-Küche-2",
        "Schalter-Küche.Schalter-Küche-1",
        "Schalter-Küche"
      ],
      "deviceDebugging": false
    }
  ]
}

**Comment by nicoh88** [comment]
Hi Oli,

der Fibaro Double Switch 2 (FGS-223) sollte eigentlich mit der aktuellsten `homebridge-devolo` Version erkannt werden, jedenfalls hatte ich hier keine Probleme.

Welche Version hast du installiert?

`npm view homebridge-devolo version`

**Comment by nicoh88** [comment]
Hi @OliTheo ,

ich habe homebridge-devolo aktualisiert und es werden jetzt die Fibaro FGS-212, FGS-213, FGS-222 und FGS-223 unterstützt. Jedenfalls, wenn man diese in den letzten Tagen angelernt hat - Devolo ändert hier gerne mal was. Da ich keine [deviceDebugging Log](https://github.com/kdietrich/homebridge-devolo#support-of-new-devices) von dir hatte, kann ich es dir nicht versprechen, aber probiere es mal.

Mit dem Befehl, eventuell noch ein `sudo` davor ...

`npm install kdietrich/homebridge-devolo#master -g --unsafe-perm`

... aktualisierst du auf die aktuelle GitHub Version.

Den Output, wenn ein Gerät nicht unterstützt wird, habe ich auch erweitert - alle nötigen Infos um eine schnelle Integration zu gewährleisten.

> Device > NAME-IM-DEVOLO < is not supported (yet) or devolo has something changed. Open an issue on github and ask for adding it.
> > Model: devolo.model.Unknown:Device
> > ProductID: 0x0000
> > ProductTypeID: 0x1000
> > Sensors: devolo.BinarySwitch:hdm:ZWave

Würde mich über Feedback freuen. 👍

**Comment by nicoh88** [comment]
Und? 😅

**Comment by OliTheo** [comment]
Hallo Nico,

Version 0.1.10

Mit dem Plugin in Homebridge habe ich kein Problem.
Möchte jedoch iobroker nutzen und habe dafür Homebridge Accessoires Manager
installiert. Hier nun das nem Module Homebridge-Devolo installiert. Diese
wiederum sendete die Fehler.

Werde am Donnerstag das ganze weiter testen.

Mit freundlichen Grüßen
Oli


Nico Hartung <notifications@github.com> schrieb am Sa. 29. Sep. 2018 um
08:44:

**Comment by nicoh88** [comment]
Hi Oli,

alles klar.
Wenn du nun die neue, aktualisierte Version **0.1.11** installierst, sollte der Fehler nicht mehr auftreten.

`npm install -g --unsafe-perm homebridge-devolo@latest`

Viel Erfolg!
Nico

**Comment by OliTheo** [comment]
Hallo Nico,

Leider funktioniert es immer noch nicht mit iobroker, muss mal sehen wie
und wo ich die Install Dateien für Devolo finde.

In homebridge selbst funktioniert alles
Mit freundlichen Grüßen
Oli

Nico Hartung <notifications@github.com> schrieb am Mi. 3. Okt. 2018 um
11:14:

**Comment by nicoh88** [comment]
Hi Oli,

alles klar. 

Eventuell fragst du mal bei @gaudes nach, der hat homebridge-devolo mit ioBroker und ioBroker.ham (Homebridge Accessory Manager) am laufen.

Gruß Nico
