### ISSUE TITLE
Gruppierungen 

### ISSUE THREAD

**Issue by kasek1975** [kdietrich/homebridge-devolo#41]
Es wäre toll wenn man in HomeKit die devolo Thermostate gruppieren könnte, wie in der devolo App. Im Wohnzimmer habe ich 3 Heizkörper und würde diese gerne zusammen steuern. sonst ist die Homebridge Devolo echt super!!

**Comment by nicoh88** [comment]
@kasek1975 Leider gibt es dafür keine Funktionalität in HomeKit. 😢 Sorry.
