### ISSUE TITLE
Fibaro Double Relais FGS-222

### ISSUE THREAD

**Issue by kasek1975** [kdietrich/homebridge-devolo#42]
Ich betreibe dieses Gerät zum öffnen meines Garagentor an der Devolo HC. Besteht die Möglichkeit, dass dieses auch über die Homebridge im Apple HomeKit nutzbar ist.

**Comment by nicoh88** [comment]
@kasek1975 Denke schon. Ich bestelle mal eins. Melde mich, wenn es von homebridge-devolo unterstüzt wird.

**Comment by kasek1975** [comment]
Genau. In Apple Home sehe ich es einfach nicht, nur über die Devolo App steuerbar.

**Comment by nicoh88** [comment]
Hi @kasek1975,

ich habe homebridge-devolo aktualisiert und es werden jetzt die Fibaro FGS-212, FGS-213, FGS-222 und FGS-223 unterstützt. Jedenfalls, wenn man diese in den letzten Tagen angelernt hat - Devolo ändert hier gerne mal was. Da ich keine [deviceDebugging Log](https://github.com/kdietrich/homebridge-devolo#support-of-new-devices) von dir hatte, kann ich es dir nicht versprechen, aber probiere es mal.

Mit dem Befehl, eventuell noch ein `sudo` davor ...
`npm install kdietrich/homebridge-devolo#master -g --unsafe-perm`
... aktualisierst du auf die aktuelle GitHub Version.

Den Output, wenn ein Gerät nicht unterstützt wird, habe ich auch erweitert um alle möglichen Infos um eine schnelle Integration zu gewährleisten.

> Device > NAME-IM-DEVOLO < is not supported (yet) or devolo has something changed. Open an issue on github and ask for adding it.
> > Model: devolo.model.Unknown:Device
> > ProductID: 0x0000
> > ProductTypeID: 0x1000
> > Sensors: devolo.BinarySwitch:hdm:ZWave

**Comment by kasek1975** [comment]
Super, vielen Dank. Ich melde mich!

**Comment by nicoh88** [comment]
Perfekt.

Gruppierungen gibt es leider nicht.
Ich würde in deinem Fall, den Schalter, der nicht benutzt wird, einfach in einen Raum "Papierkorb" verschieben.

Ich mache hier zu. 👍

**Comment by kasek1975** [comment]
Ok. Das mit dem Raum Papierkorb habe ich versucht, aber wenn man den Raum bei einem Schalter ändert wandert der andere automatisch mit. Geht leider nicht.

**Comment by nicoh88** [comment]
@kasek1975 

Ab der aktuellen GitHub-Master-Version ...

`npm install kdietrich/homebridge-devolo#master -g --unsafe-perm`

... gibt es jetzt für die `config.json` einen neuen Parameter `switchBlacklistDoubleRelaySwitch`. Mehr dazu [hier](https://github.com/kdietrich/homebridge-devolo#optional-parameters).

Viel Erfolg! 🍀

**Comment by kasek1975** [comment]
Danke nochmal, konnte aus gesundheitlichen Gründen mich nicht melden. Die Erweiterungen sind jetzt auch in der offiziellen Version. Welchen Befehl muss ich denn nutzen um jetzt auf diese upzudaten?

**Comment by nicoh88** [comment]
Hallo @kasek1975,

du solltest mit dem Befehl `npm install homebridge-devolo -g --unsafe-perm` die Version `0.1.12` bekommen, welche auch die Erweiterungen enthält.
