### ISSUE TITLE
Danfoss Heizkörperthermostat living connect Z

### ISSUE THREAD

**Issue by sebi1411** [kdietrich/homebridge-devolo#44]
Hallo zusammen,

erste einmal vielen Dank für die echt coole Integration der Devolo HC in homebrdige von kdietrich. Endlich kann ich meine Devolo HC über HomeKit steuern. 

Nun zu meinem "Problem": Ganz pfiffig hab ich mir für die kalte Jahreszeit zwei Danfoss Heizkörperthermostat living connect Z zugelegt um die verbleibenden Räume noch smart zu machen. Die Einbindung in die HC als devolo Heizkörperthermostat hat einwandfrei funktioniert. Nun noch fix die homebridge neu starten und dann sollte ja alles laufen 😉 Leider nicht so ganz. Die Heizkörperthermostat werden zwar erkannt (siehe Log), jedoch scheinbar nicht unterstützt und können damit auch nicht gesteuert werden. 

>[2018-10-5 14:43:10] [Devolo] HBDevoloPlatform > Central Unit found.
>Device > Heizung Büro < is not supported (yet) or devolo has something changed. Open an issue on github and ask for adding it.
> Model: unk.model.Unknown:Device
> ProductID: 0x0004
> ProductTypeID: 0x0005
> Sensors: devolo.MultiLevelSwitch:hdm:ZWave:EC2D5629/13
>
>Device > Heizung Badezimmer < is not supported (yet) or devolo has something changed. Open an issue on github and ask for adding it.
> Model: unk.model.Unknown:Device
> ProductID: 0x0004
> ProductTypeID: 0x0005
> Sensors: devolo.MultiLevelSwitch:hdm:ZWave:EC2D5629/12

Habt ihr die Möglichkeit auch die Danfoss Heizkörperthermostat living connect Z zu unterstützen? Gerne liefere ich euch weitere Informationen. 

Ich danke euch schonmal vielmals.

Viele Grüße
Sebastian

**Comment by nicoh88** [comment]
Hi Sebastian,

das kriegen wir sicher hin. 👍

Kannst du mir mal einen Screenshot von der Geräteübersicht aus myDevolo machen? Mich interessiert wie die Danfoss Heizkörperthermostate dargestellt werden. 

Danke

**Comment by sebi1411** [comment]
Hi,

wow, die Antwort kam aber fix. Klar, sehr gerne. Anbei das Foto.
![img_0440](https://user-images.githubusercontent.com/43882968/46540729-722faf00-c8ba-11e8-8041-44c6b81ea6eb.png)

Zur Info: Heizung Badezimmer ist als "anderes ZWave" Gerät gekoppelt, Heizung Büro als Devolo Gerät und Heizung Wohnzimmer ist das Original Devolo Heizkörperthermostat, dass bereits wunderbar per HomeKit funktioniert.

Viele Grüße und schon einmal vielen Dank
Sebastian

**Comment by nicoh88** [comment]
Hi Sebastian,

dank dir, die Geräte sehen aber vom Funktionsumfang in Devolo HomeControl identisch aus oder?
Wenn du mal Computer bist, benötige ich noch einen Screenshot von der Geräteübersicht auf mydevolo.de.

Danke

**Comment by sebi1411** [comment]
Hi Nico,

der Funktionsumfang ist komplett identisch. Hier die gewünschten Screenshots.
![bildschirmfoto 2018-10-05 um 16 33 31](https://user-images.githubusercontent.com/43882968/46541592-be7bee80-c8bc-11e8-90e0-dbc1fa6901a9.png)
![bildschirmfoto 2018-10-05 um 16 33 51](https://user-images.githubusercontent.com/43882968/46541593-be7bee80-c8bc-11e8-864a-b6a599822032.png)
![bildschirmfoto 2018-10-05 um 16 34 00](https://user-images.githubusercontent.com/43882968/46541594-bf148500-c8bc-11e8-8ea1-cbbeef7c5466.png)
![bildschirmfoto 2018-10-05 um 16 35 45](https://user-images.githubusercontent.com/43882968/46541595-bf148500-c8bc-11e8-899b-ebe14902034d.png)

Viele Grüße
Sebastian

**Comment by nicoh88** [comment]
Hi @sebi1411,

dank dir. Wenn du als `root` nun die aktuelle GitHub-Master-Version installierst und deine Homebridge neustartest, sollten deine Danfoss Living Connect Z erkannt werden.

```
npm install kdietrich/homebridge-devolo#master -g --unsafe-perm
service homebridge restart
```

Leider, haben wir mit den Heizkörperthermostaten ein kleines **kosmetisches Problem**. Im Status wird immer Raum XXX wird geheizt angezeigt - auch wenn die Wunschtemperatur 5° ist oder die Wunschtemperatur bereits erreicht ist. 
**Warum?** Im Devolo HomeControl zeigen uns die Heizkörperthermostate auch nicht die aktuelle Temperatur im Raum an, sondern nur die Wunschtemperatur - obwohl das Heizkörperthermostat die Funktion, intern, ja haben muss, sonst wüsste es ja nicht, wann es das Ventil wieder schließen muss. Aus diesem Grund können wir in Homebridge mit dieser aktuellen Raumtemperatur auch nicht arbeiten. 😢 Sonst könnte man in Quellcode sagen: _Wenn Raumtemperatur über Wunschtemperatur..._
Des Weiteren gibt es den Modus "_Aus_", "_Heizen_", "_Kühlen_" und "_Automatisch_". Was bei den Heizkörperthermostaten ja keinen Sinn macht.

**Was wäre deine Wunschlösung für dieses Problem?**

**Comment by sebi1411** [comment]
Hi @nicoh88,

wow, was ne Geschwindigkeit!!!!! Es läuft🥇 Vielen lieben Dank!

Ich habe davon schon in einem anderen Issue gelesen. Ehrlich gesagt hat mich das kosmetische Problem bisher nicht gestört. Ich war froh eine Lösung zu haben, die es ermöglicht die Devolo HC ins HomeKit einzubinden. 

Wenn ich mir jedoch etwas wünschen dürfte, würde ich mich auch über eine "korrektere" Beschreibung freuen.Ich gebe dir durchaus recht, dass das Thermostat ja wissen muss wie viel Grad im Raum erreicht sind, auch wenn diese aufgrund zur Nähe zur Heizung nicht unbedingt die Raumtemperatur widerspiegelt.  Hast du bereits Kontakt zu Devolo gehabt? 

Viele Grüße
Sebastian

**Comment by nicoh88** [comment]
Hi @sebi1411,

perfekt, freut mich.

Was meinst du mit "korrektere" Beschreibung? Für was eine Beschreibung? (Ich kann nur Wünsche für das `homebridge-devolo` Plugin entgegennehmen 😄)

Ja naja, Devolo sagt dazu nicht viel. Für Devolo funktioniert ihr System und wir wissen aus den letzten Jahren, dass nur selten Anpassungen gemacht werden. Bisher, niemals für ein Drittsystem wie Homebridge oder eine Drittprodukt von Fibaro oder Qubino. 😭 

Gruß Nico

**Comment by mavinion** [comment]
Hallo, ich habe 0.1.14 drauf

aber meine Danfoss werden wohl auch nicht erkannt.

> Model: unk.model.Danfoss:Thermostat                                                                                                                                           
> ProductID: 0x0004                                                                                                                                                             
> ProductTypeID: 0x0005                                                                                                                                                         
> Sensors: devolo.MultiLevelSwitch:hdm:ZWave:C2B29409/22

**Comment by nicoh88** [comment]
@mavinion 

Hi, scheinbar hat Devolo, mit dem Firmware-Update vom 2. Mai 2019, bei einigen Geräten die Gerätebezeichnung geändert, deshalb das Problem.

Habe die Änderungen im GitHub-Master eingespielt. 
Bitte testen.

**Comment by mavinion** [comment]
danke, klappt einwandfrei

**Comment by eyk2000** [comment]
Hallo, bei mir haben sich nach dem Update die Qubino Flush 1D Unterputz-Schalter "verabschiedet" und 2 Wassersensoren von Fibaro.
Keine Ahnung was Devolo da wieder verschlimmbessert hat...?!
Hier die Daten der Geräte:

Device > Deckenlicht < is not supported (yet) or devolo has something changed. Open an issue on github and ask for adding it.                     
> Model: unk.model.Netichome:D:Module                                                                                                             
> ProductID: 0x0053                                                                                                                               
> ProductTypeID: 0x0002                                                                                                                           
> Sensors: devolo.BinarySwitch:hdm:ZWave:C80D9DEE/29,devolo.BinarySensor:hdm:ZWave:C80D9DEE/29#4

und:
Device > Wassermelder Wanne < is not supported (yet) or devolo has something changed. Open an issue on github and ask for adding it.              
> Model: unk.model.Unknown:Device                                                                                                                 
> ProductID: 0x1001                                                                                                                               
> ProductTypeID: 0x0b00                                                                                                                           
> Sensors: devolo.BinarySensor:hdm:ZWave:C80D9DEE/36#1,devolo.LastActivity:hdm:ZWave:C80D9DEE/36#1,devolo.MultiLevelSensor:hdm:ZWave:C80D9DEE/36#2
,devolo.MultiLevelSensor:hdm:ZWave:C80D9DEE/36#SensorAlarm(0),devolo.MultiLevelSensor:hdm:ZWave:C80D9DEE/36#SensorAlarm(5),devolo.BinarySwitch:hdm
:ZWave:C80D9DEE/36#1

Vielen Dank für die Unterstützung und den Support

**Comment by eyk2000** [comment]
Okay, einen hab ich noch vergessen...:
Device > Wassermelder Spühle < is not supported (yet) or devolo has something changed. Open an issue on github and ask for adding it.             
> Model: unk.model.Fibaro:Flood                                                                                                                   
> ProductID: 0x1002                                                                                                                               
> ProductTypeID: 0x0b01                                                                                                                           
> Sensors: devolo.BinarySensor:hdm:ZWave:C80D9DEE/35#Alarm(5),devolo.LastActivity:hdm:ZWave:C80D9DEE/35#Alarm(5),devolo.MultiLevelSensor:hdm:ZWave
:C80D9DEE/35,devolo.BinarySensor:hdm:ZWave:C80D9DEE/35#Alarm(7),devolo.LastActivity:hdm:ZWave:C80D9DEE/35#Alarm(7)

**Comment by eyk2000** [comment]
Obwohl beide Wassermelder von Fibaro identisch sind, werden sie unterschiedlich "erkannt".....?!

**Comment by lemisoft** [comment]
Hallo,

die Danfoss laufen laufen bei mir mit der neuen Version perfekt - so wie im Augenblick das ganze System. Selbst von außerhalb des Netzwerkes ist der Status mit Nu da. Klasse Arbeit!

Zur Frage zum gewünschten Verhalten der HKT: Ideal wäre natürlich, wenn die Dinger im UI nur dann „aufleuchten“, wenn wie Ist-Temperatur ungleich der Zieltemperatur ist. Da das aber bei Devolo wohl nicht geht würde ich einfach unterstellen, dass die Zieltemperatur erreicht ist - also die Zieltemperatur erreicht ist. Der Vorteil wäre, dass nicht alle HKT im UI „leuchten“ und andere Komponenten dann besser auffallen...

Ich bin gespannt welches Idealbild andere User haben...

**Comment by nicoh88** [comment]
Hallo @eyk2000 

bzgl. deiner Wassermelder machst du bitte mit den Infos Model, ProductID, ProductTypeID und Sensor ein extra Issue auf. Danke

Für den Qubino Flush 1D hast du es ja bereits getan.

Danke
