### ISSUE TITLE
Popp Z-Weather

### ISSUE THREAD

**Issue by MikeyRZW** [kdietrich/homebridge-devolo#47]
Hi zusammen,
könnt ihr einem Anfänger unterstützen?

Jetzt habe ich in das Devolo System eine Wetterstation von Popp "installiert" (Z-Weather).
In der Devolo Oberfläche erscheint das Gerät mit seinen Werten. In ioBroker nicht, da die homebridge-devolo das Gerät logischer Weise nicht abfragt.

Auf GitHub gibt es folgenden Hinweis für neue Geräte:

Zitat:
Support of new devices

I'm happy to provide support for new devices. If you own an unsupported device you can provide me a debug log making the device integration easier for me. In order to do so set the config parameter deviceDebugging to true and run the following command: homebridge -D | tee debugoutput.log. The command will auto-finish after a while and create a textfile named debugoutput.log. Please attach this log file to your github issue.
Zitat Ende

Den Cofig Parameter in die Config Datei des Adapters einzutragen ist verständlich...
,aber wie führe ich ein Command im ioBroker aus ???

Gruß aus NRW
Mikey

**Comment by kdietrich** [comment]
Hallo Mikey,

ich nehme mal an, dass ioBroker irgendwo eine Log-Datei des Adapters anlegt. Diese müsstest du finden und mir zukommen lassen.

Viele Grüße
Kevin

**Comment by kdietrich** [comment]
Ja, eine temporäre Portweiterleitung des SSH-Ports wäre toll. Für alles weitere schreibst du mir am besten deine E-Mail Adresse. ;-)

**Comment by MikeyRZW** [comment]
Michael@mahlmann.org

**Comment by nicoh88** [comment]
@MikeyRZW: Habe dich mal kontaktiert.

**Comment by kdietrich** [comment]
Hallo Mikey,

konnte mir die Log-Datei ziehen.
Zur Doku: Du klickst auf Instanzen und stellst auf den Expertenmodus. Anschließend setzt du das Log-Level von ham.0 auf debug. Nun öffnest du die ham.0 Konfiguration und trägst wie beschrieben `"deviceDebugging": true` ein. Nach einem Neustart der ham.0 Instanz findest du unter Log die benötigte Log-Datei.

Ich melde mich sobald ich bezüglich der Popp-Wetterstation weiter bin.

**Comment by kdietrich** [comment]
Log-Datei:

---

### DEVICES

```
{
        "UID": "hdm:ZWave:D0867FD6/47",
        "properties": {
            "pendingOperations": null,
            "batteryLow": false,
            "zoneId": "hz_8",
            "isSecurelyIncluded": false,
            "zone": "Terasse",
            "prodTypeID": "0x0100",
            "statisticsUID": "st.hdm:ZWave:D0867FD6/47",
            "secureInclusionCode": 0,
            "prodID": "0x0400",
            "status": 1,
            "settingUIDs": [
                "gds.hdm:ZWave:D0867FD6/47"
            ],
            "manID": "0x0154",
            "batteryLevel": 70,
            "icon": "icon_38",
            "operationStatus": null,
            "description": null,
            "wrongDevicePaired": false,
            "isOwn": true,
            "deviceModelUID": "devolo.model.Unknown:Type:Device",
            "itemName": "Wetterstation",
            "elementUIDs": [
                "devolo.Meter:hdm:ZWave:D0867FD6/47",
                "devolo.MultiLevelSensor:hdm:ZWave:D0867FD6/47#MultilevelSensor(1)",
                "devolo.MultiLevelSensor:hdm:ZWave:D0867FD6/47#MultilevelSensor(3)",
                "devolo.MultiLevelSensor:hdm:ZWave:D0867FD6/47#MultilevelSensor(5)",
                "devolo.MultiLevelSensor:hdm:ZWave:D0867FD6/47#MultilevelSensor(6)",
                "devolo.MultiLevelSensor:hdm:ZWave:D0867FD6/47#MultilevelSensor(9)",
                "devolo.MultiLevelSensor:hdm:ZWave:D0867FD6/47#MultilevelSensor(11)",
                "devolo.BinarySwitch:hdm:ZWave:D0867FD6/47"
            ]
        },
        "attributes": {},
        "objectClass": [
            "com.devolo.fi.widget.DeviceWidget",
            "com.devolo.fi.widget.BaseWidget",
            "com.devolo.fi.widget.Widget",
            "com.devolo.fi.async.base.AsyncFunctionalItem",
            "com.prosyst.mbs.services.fim.FunctionalItem"
        ],
        "tags": []
    }
```

---

### SENSORS

```
    {
        "UID": "devolo.Meter:hdm:ZWave:D0867FD6/47",
        "properties": {
            "pendingOperations": null,
            "sensorType": null,
            "guiEnabled": true,
            "sinceTime": 1542194412114,
            "currentValue": 0,
            "operationStatus": null,
            "type": 2,
            "widgetUID": "hdm:ZWave:D0867FD6/47",
            "totalValue": 5.95221,
            "itemId": null
        },
        "attributes": {},
        "objectClass": [
            "com.devolo.fi.label.MeterFI",
            "com.devolo.fi.widget.WidgetElement",
            "com.prosyst.mbs.services.fim.FunctionalItem"
        ],
        "tags": []
    },
    {
        "UID": "devolo.MultiLevelSensor:hdm:ZWave:D0867FD6/47#MultilevelSensor(1)",
        "properties": {
            "value": 11.8,
            "unit": 0,
            "sensorType": "temperature",
            "guiEnabled": true,
            "type": 2,
            "widgetUID": "hdm:ZWave:D0867FD6/47",
            "itemId": null
        },
        "attributes": {},
        "objectClass": [
            "com.devolo.fi.label.MultiLevelSensorFI",
            "com.devolo.fi.widget.WidgetElement",
            "com.prosyst.mbs.services.fim.FunctionalItem"
        ],
        "tags": []
    },
    {
        "UID": "devolo.MultiLevelSensor:hdm:ZWave:D0867FD6/47#MultilevelSensor(3)",
        "properties": {
            "value": 0,
            "unit": 0,
            "sensorType": "light",
            "guiEnabled": true,
            "type": 2,
            "widgetUID": "hdm:ZWave:D0867FD6/47",
            "itemId": null
        },
        "attributes": {},
        "objectClass": [
            "com.devolo.fi.label.MultiLevelSensorFI",
            "com.devolo.fi.widget.WidgetElement",
            "com.prosyst.mbs.services.fim.FunctionalItem"
        ],
        "tags": []
    },
    {
        "UID": "devolo.MultiLevelSensor:hdm:ZWave:D0867FD6/47#MultilevelSensor(5)",
        "properties": {
            "value": 86,
            "unit": 0,
            "sensorType": "humidity",
            "guiEnabled": true,
            "type": 2,
            "widgetUID": "hdm:ZWave:D0867FD6/47",
            "itemId": null
        },
        "attributes": {},
        "objectClass": [
            "com.devolo.fi.label.MultiLevelSensorFI",
            "com.devolo.fi.widget.WidgetElement",
            "com.prosyst.mbs.services.fim.FunctionalItem"
        ],
        "tags": []
    },
    {
        "UID": "devolo.MultiLevelSensor:hdm:ZWave:D0867FD6/47#MultilevelSensor(6)",
        "properties": {
            "value": 5,
            "unit": 0,
            "sensorType": "Velocity",
            "guiEnabled": true,
            "type": 2,
            "widgetUID": "hdm:ZWave:D0867FD6/47",
            "itemId": null
        },
        "attributes": {},
        "objectClass": [
            "com.devolo.fi.label.MultiLevelSensorFI",
            "com.devolo.fi.widget.WidgetElement",
            "com.prosyst.mbs.services.fim.FunctionalItem"
        ],
        "tags": []
    },
    {
        "UID": "devolo.MultiLevelSensor:hdm:ZWave:D0867FD6/47#MultilevelSensor(9)",
        "properties": {
            "value": 100.8,
            "unit": 0,
            "sensorType": "Barometric Preassure",
            "guiEnabled": true,
            "type": 2,
            "widgetUID": "hdm:ZWave:D0867FD6/47",
            "itemId": null
        },
        "attributes": {},
        "objectClass": [
            "com.devolo.fi.label.MultiLevelSensorFI",
            "com.devolo.fi.widget.WidgetElement",
            "com.prosyst.mbs.services.fim.FunctionalItem"
        ],
        "tags": []
    },
    {
        "UID": "devolo.MultiLevelSensor:hdm:ZWave:D0867FD6/47#MultilevelSensor(11)",
        "properties": {
            "value": 9.6,
            "unit": 0,
            "sensorType": "Dew Point",
            "guiEnabled": true,
            "type": 2,
            "widgetUID": "hdm:ZWave:D0867FD6/47",
            "itemId": null
        },
        "attributes": {},
        "objectClass": [
            "com.devolo.fi.label.MultiLevelSensorFI",
            "com.devolo.fi.widget.WidgetElement",
            "com.prosyst.mbs.services.fim.FunctionalItem"
        ],
        "tags": []
    },
    {
        "UID": "devolo.BinarySwitch:hdm:ZWave:D0867FD6/47",
        "properties": {
            "targetState": 1,
            "state": 1,
            "pendingOperations": null,
            "guiEnabled": true,
            "operationStatus": null,
            "type": 1,
            "widgetUID": "hdm:ZWave:D0867FD6/47",
            "itemId": null,
            "switchType": "basic"
        },
        "attributes": {},
        "objectClass": [
            "com.devolo.fi.control.BinarySwitchFI",
            "com.devolo.fi.widget.WidgetElement",
            "com.devolo.fi.async.base.AsyncFunctionalItem",
            "com.prosyst.mbs.services.fim.FunctionalItem"
        ],
        "tags": []
    }
```

@MikeyRZW Welche Werte aus der Popp Wetterstation hättest du denn gerne in Apple Home?

**Comment by MikeyRZW** [comment]
Hi,
ein Timestamp, wann das Gerät zuletzt online war, oder sich letzmalig gemeldet hat wäre auch schön

**Comment by MikeyRZW** [comment]
Hi,
seit ihr mit diesem Thema noch beschäftigt ?

**Comment by nicoh88** [comment]
@MikeyRZW 

Eventuell komme ich zwischen dem Fest dazu - kann es aber nicht versprechen.
Wenn dann werde ich dir aber nur ...

- Temperatur
- Luftfeuchtigkeit
- Taupunkt
- Luftdruck
- Windgeschwindigkeit
- Helligkeit
- Batterieladung (vielleicht, muss ich mal schauen)

... in HomeKit anzeigen lassen können.

Der Timestamp auf keinem Fall, das passt auch irgendwie nicht zr Philosophie von HomeKit / Homebridge. 

Gruß Nico

**Comment by MikeyRZW** [comment]
der Timestamp war auch eher "nice to have" ;)

**Comment by MikeyRZW** [comment]
Hi,
ich habe noch ein Manual dazu gefunden :)
[z-weather-005206.pdf](https://github.com/kdietrich/homebridge-devolo/files/2710945/z-weather-005206.pdf)

**Comment by MikeyRZW** [comment]
@nicoh88
bist du weitergekommen?

**Comment by MikeyRZW** [comment]
Hi Nico,
wie kann ich dir die Zugangsdaten zukommen lassen?

**Comment by nicoh88** [comment]
blog@loggn.de

**Comment by nicoh88** [comment]
Nur der Vollständigkeit halber:

```
Device > Wetterstation < is not supported (yet) or devolo has something changed. Open an issue on github and ask for adding it.
> Model: devolo.model.Unknown:Type:Device
> ProductID: 0x0400
> ProductTypeID: 0x0100
> Sensors: devolo.Meter:hdm:ZWave:D0867FD6/47,devolo.MultiLevelSensor:hdm:ZWave:D0867FD6/47#MultilevelSensor(1),devolo.MultiLevelSensor:hdm:ZWave:D0867FD6/47#MultilevelSensor(3),devolo.MultiLevelSensor:hdm:ZWave:D0867FD6/47#MultilevelSensor(5),devolo.MultiLevelSensor:hdm:ZWave:D0867FD6/47#MultilevelSensor(6),devolo.MultiLevelSensor:hdm:ZWave:D0867FD6/47#MultilevelSensor(9),devolo.MultiLevelSensor:hdm:ZWave:D0867FD6/47#MultilevelSensor(11),devolo.BinarySwitch:hdm:ZWave:D0867FD6/47
```

**Comment by nicoh88** [comment]
Done. 👍 

**Temperatur**, **Luftfeuchtigkeit**, **Helligkeit** und **Batteriestatus** konnte ich ganz offiziell hinzufügen und in Apple Home anzeigen lassen. (HomeKit Characteristics)

![bildschirmfoto 2019-01-07 um 00 24 22](https://user-images.githubusercontent.com/264264/50743096-068c1380-1214-11e9-9af3-1cc39baf5ee3.png)

**Taupunkt**, **Windgeschwindigkeit** und **Luftdruck** kann man sich nur in anderen HomeKit Apps, wie Eve, anzeigen lassen. (Custom Characteristics)

![img_3656](https://user-images.githubusercontent.com/264264/50743112-4521ce00-1214-11e9-97f8-88215c650ddc.jpg)

Ich hoffe, dass im ioBroker / HAM auch die Custom Characteristics mit angezeigt werden.

Mit dem Terminal-Befehl ...
`npm install kdietrich/homebridge-devolo#master -g --unsafe-perm`
... installierst du die aktuelle GitHub-Master Version.

Viel Erfolg,
Nico

**Comment by MikeyRZW** [comment]
ich habe den Adapter per npm aktualisiert, den Adapter neu gestartet, den Rechner neu gestartet,
es wird aber kein neues Objekt für die Wetterstation angelegt

**Comment by nicoh88** [comment]
Hi @MikeyRZW,

wie hast du das Plugin aktualisiert?

Wenn du es mit dem Befehl aktualisiert hättest, hätte es gehen müssen. Daher, hast du sicher irgendetwas anders gemacht oder HAM erwartet einen anderen Befehl.

Kenne mich mit ioBroker und HAM nicht aus.

**Comment by MikeyRZW** [comment]
Hi,
ich habe deinen Konsolenbefehl kopiert und im Terminalfenster ausgeführt.
beim ersten mal kam die Meldung das 4 packages geupdatet wurden.

![image](https://user-images.githubusercontent.com/45110596/50754156-fe07fd00-1254-11e9-9a6e-af6e2762488d.png)

**Comment by nicoh88** [comment]
Folgendes habe ich ausgeführt.

```
su - 
cd /opt/iobroker/node_modules/iobroker.ham/node_modules
# Ohne `-g` (global), Installation startet dann in das Verzeichnis in dem man sich befindet.
npm install --unsafe-perm kdietrich/homebridge-devolo#master
```

Bitte Dienst oder komplettes System mal neustarten und prüfen.

Gruß Nico

**Comment by MikeyRZW** [comment]
das war es wohl...
DANKE für deine Bemühungen.

![image](https://user-images.githubusercontent.com/45110596/50755708-20e8e000-125a-11e9-8fc2-2845c95bef1c.png)

**Comment by nicoh88** [comment]
Schön, freut mich.

Würdest du es bitte mal ein paar Tage testen und dich dann nochmal melden? Wenn alles soweit gut ist, würde ich die Version dann auch für den Rest der Welt zugänglich machen. 👍 

Gruß Nico

**Comment by MikeyRZW** [comment]
Hi,
@nicoh88 
der Adapter läuft bis jetzt stabil

![image](https://user-images.githubusercontent.com/45110596/51014588-ee482b80-1568-11e9-8edc-ec92a0b85b9e.png)
![image](https://user-images.githubusercontent.com/45110596/51014646-27809b80-1569-11e9-8587-f91f4eebd160.png)
