### ISSUE TITLE
Exception und Endlosloop bei Start von Homebridge

### ISSUE THREAD

**Issue by tomsprenger** [kdietrich/homebridge-devolo#49]
Hallo,

nach der Konfiguration des Homebridge plugin for Devolo Home Control (homebridge-devolo v0.1.12) erhalte ich im Log folgende Fehlermeldung und Homebridge fällt in einen endlosen Restart.

--- LOGFILE ---

\###### ZONES START ######
[
    {
            
<...>

        },
        "attributes": {},
        "objectClass": [
            "com.devolo.fi.page.Grouping",
            "com.devolo.fi.page.Page",
            "com.prosyst.mbs.services.fim.FunctionalItem"
        ],
        "tags": []
    }
]
\###### ZONES END ######
\###### ZONES START ######
undefined
\###### ZONES END ######

/homebridge/node_modules/node-devolo/dist/DevoloApi.js:76
                callback(err);
                ^
TypeError: Cannot read property '0' of undefined
    at /homebridge/node_modules/node-devolo/dist/Devolo.js:409:38
    at /homebridge/node_modules/node-devolo/dist/DevoloApi.js:184:17
    at IncomingMessage.<anonymous> (/homebridge/node_modules/node-devolo/dist/DevoloApi.js:76:17)
    at IncomingMessage.emit (events.js:182:13)
    at Socket.socketCloseListener (_http_client.js:356:11)
    at Socket.emit (events.js:187:15)
    at TCP._handle.close (net.js:610:12)

--- END LOGFILE ---

Kann mir jemand weiterhelfen?

Gruss

-- TOM.

**Comment by nicoh88** [comment]
Hi Tom,

du hast zwei Probleme:

1. Solltest du `deviceDebugging` in deiner `config.json` auf `false` setzen.
2. Homebridge-devolo ist leider nicht NOCH NICHT (@kdietrich #48) mit node 9, 10, 11 oder höher kompatibel - bitte installiere node v8.

Du kannst dazu diese meine HowTo verwenden:
https://www.loggn.de/apple-home-homekit-devolo-geraete-mit-der-apple-app-steuern-homebridge/

Würde mich über eine Rückmeldung freuen.

Viele Grüße
Nico

**Comment by tomsprenger** [comment]
Hi Nico,

danke für deine prompte Antwort.

config.json habe ich angepasst.

Betreffend node 8: homebridge läuft bei mir auf einem Synology NAS. ich benutze das "Synology Package for Homebridge Docker” <https://github.com/oznu/homebridge-syno-spk> (Version 1.0.7). Das Package läuft als Docker-Image. Ich sehe nicht grad, wie ich da einen Downgrade von node 11 —> node 8 machen kann. Würdest du mir von der Verwendung des Packages abraten? 

Soll ich besser auf eine VM wechseln und deinem HowTo folgen?

Besten Gruss

— TOM.

**Comment by kdietrich** [comment]
Hallo Tom,

installiere bitte die neueste master-Version und teste es noch mal: `npm install kdietrich/homebridge-devolo#master -g --unsafe-perm`.

Viele Grüße
Kevin

**Comment by tomsprenger** [comment]
Hallo Kevin,

die neuste Version (homebridge-devolo v0.1.13-dev) funktioniert tadellos! 👍🏻

Gruss & herzlichen Dank für deine Unterstützung 

— TOM.
