### ISSUE TITLE
neuer ham Adapter

### ISSUE THREAD

**Issue by MikeyRZW** [kdietrich/homebridge-devolo#50]
Hi,
es gibt eine neue Version vom ham Adapter.
Gibt es aus Sicht vom homebridge-devolo etwas was gegen ein Update spricht?

**Comment by nicoh88** [comment]
Hi @MikeyRZW,

`homebridge-devolo` ist ein Standard Homebridge Plugin. Der HAM-Adapter ist genau für solche Homebridge Plugins. Wir prüfen nicht ob unser Plugin kompatibel ist, dass ist der Aufgabe der Entwickler vom HAM-Adapter. 
Ich gehe aber davon aus, dass die wissen was sie tun - somit solltest du das Update ohne Bedenken durchführen können.

Viele Grüße
