### ISSUE TITLE
Devolo via Homebridge nicht Remote erreichbar

### ISSUE THREAD

**Issue by lemisoft** [kdietrich/homebridge-devolo#51]
Hallo,

sicher kein Bug, aber vielleicht hat jemand eine Idee: Devolo mit HomeBridge und Hue funktionieren problemlos mit HomeKit - solange ich zuhause im WLAN bin. Sobald ich unterwegs bin erreiche ich zwar noch HomeKit und Hue, aber nicht mehr Devolo mit HomeBridge. Alle Devolo-Komponeneten sind nicht erreichbar.  Sobald ich wieder im WLAN bin geht es wieder.

Gekommen ist dies wohl mit einem Routerwechsl von Speedport auf eine Fritzbox 7590... vermutlich ein Config-Problem, nur wo?

Viele Grüße

**Comment by nicoh88** [comment]
@lemisoft 

Hast du einen HomeKit Hub / Steuerzentrale konfiguriert?

Viele Grüße

**Comment by lemisoft** [comment]
Hi Nico, 

erst einmal Danke für die schnelle Antwort! Ja, die Zentrale ist konfiguriert - es geht auch alles mit der Apple Home-App solange ich im heimischen WLAN angemeldet bin. Sobald ich aber unterwegs bin kann ich nur noch die Hue-Lampen über die Home-App steuern und nichts, dass über die Homebridge angebunden ist. Die Komponenten zeigen „Keine Antwort“. 

Viele Grüße,
Andreas




-- 
lemisoft • Andreas Lehmann
Nymphenburger Str. 147 • 80634 München • Germany
Tel: +49-89-14729332 • Mobile: +49-172-8569069
Fax: +49-89-14729334 • http://www.lemisoft.de
Skype: lemisoft • Twitter: @lemisoft

**Comment by nicoh88** [comment]
Hi Andreas,

welches Gerät ist die Steuerzentrale?
Auf der Steuerzentrale im heimischen WLAN werden die Geräte ordentlich angezeigt?
Hast du mal die Steuerzentrale und auch dein iPhone (welches unterwegs Probleme macht) neugestartet? 
Wir reden von den gleichen "Haus" oder unterschiedlichen "Häusern" in Apple Home?

Viele Grüße

**Comment by lemisoft** [comment]
Hi Nico,

ein Neustart des Apple TV hat geholfen - Danke Dir! Spannend, denn im WLAN hat alles tadellos funktioniert und und außerhalb Güter WLAN ging alles außer die Bridge... 

Viele Grüße aus Nandlstadt,
Andreas 

 
-- 
lemisoft • Andreas Lehmann
Nymphenburger Str. 147 • 80634 München • Germany
Tel: +49-89-14729332 • Mobile: +49-172-8569069
Fax: +49-89-14729334 • http://www.lemisoft.de
Skype: lemisoft • Twitter: @lemisoft

**Comment by nicoh88** [comment]
Freut mich.

Noch zwei kurze Fragen:
1. Hast du homebridge-devolo erst vor ein paar Tagen eingerichtet, oder schon länger?
2. Nutzt den AppleTV nur als HomeKit Zentrale oder auch zum aktivieren steuern von HomeKit Geräten?

Gruß Nico

**Comment by lemisoft** [comment]
Hallo Nico,

die beantworte ich doch gerne...

1. Die Homebridge läuft schon fast ein Jahr - natürlich hin und wieder mit Update
2. Apple TV ist nur die Schnittstelle zur Devolo-Zentrale für Home-App und Siri.

Viele Grüße und ein feines Wochenende,
Andreas

-- 
Andreas Lehmann
Hofenfelsstraße 54 • 80637 München • Germany
Tel: +49-89-14729332 • Mobile: +49-172-8569069
Fax: +49-89-14729334 • www.lemisoft.de
