### ISSUE TITLE
Devolo Tür- Fensterkontakt aktualisiert sich nicht

### ISSUE THREAD

**Issue by kasek1975** [kdietrich/homebridge-devolo#53]
Ich habe an meinem Garagentor einen Tür- Fensterkontakt von Devolo angebracht, den ich auch an der Haustür nutze. Eine Zeit lang war alles ok, wenn ich das Garagentor geöffnet habe, dann zeigte dr Kontakt im Homekit auch an, dass das Tor geöffnet ist. Seit einem Moment zeigt er das nicht mehr an, laut Anzeige ist er geschlossen. In der Devolo App wird allerdings geöffnet angezeigt.

Der Kontakt an der haustür aktualisiert ganz normal in der Devolo App und auch in der Homekit app. Also wenn ich die Haustür öffne, dauert es kurz und er zeigt in der Homekit offen an.

Was muss ich machen, damit dies beim Garagentor auch wieder funktioniert?

In der Garage habe ich eine Schaltsteckdoese installiert, damit ich hier auch eine Repeater Funktion habe. Der Fibaro Schalter ist auch immer online und ich kann das Tor immer aufmachen...

**Comment by nicoh88** [comment]
Hi @kasek1975,

vermutlich wird ein Homebridge Neustart das Problem lösen.
Weil der Kontakt muss ja in Ordnung sein, da es in der Devolo-App korrekt funktioniert.

Du hast aber kein `fakeGaragedoor` konfiguriert? Oder?

Gruß Nico

**Comment by kasek1975** [comment]
Hi Nico, ein fakeGaragedoor habe ich nicht konfiguriert.
Ich starte den Pi nachts mit einem Cronjob neu, daher wundere ich mich über das Verhalten. Mache ich gleich aber nochmal aus und starte dann neu, mal sehen ob das eine Änderung bringt.
Gruß Carsten

**Comment by kasek1975** [comment]
Hat leider nicht funktioniert. Kann als nächstes aus meiner Sicht nur den Kontakt aus der Devolo nehmen und nochmal neu integrieren. Eine andere Idee hätte ich jetzt nicht. Oder hast du noch einen Tipp?

**Comment by MikeyRZW** [comment]
Hi, hast du mal die Zentrale neu gestartet?
Die hat sich bei mir letzte Woche auch irgendwie weggehangen.
Standard Devolo ging, der Rest aber nicht.

**Comment by kasek1975** [comment]
Nein das habe ich nich nicht gemacht. Teste ich nachher mal, danke!

**Comment by kasek1975** [comment]
Hat nichts gebracht. Zentrale ist neu gestartet. Wenn das Tor öffnet ändert sich weiterhin nichts.

**Comment by nicoh88** [comment]
Hi @kasek1975 

ist der Devolo Tür- & Fensterkontakt sehr neu? Eventuell hat Devolo eine neue Revision oder eine geänderte / verbesserte Firmware...

Probiere bitte nochmal das Ab- und wieder Anlernen des Kontakts und danach natürlich ein Homebridge Neustart. Wenn das nicht funktioniert, müsstest du mich mal per SSH auf dein System lassen, dann muss ich mir das Problem mal genauer anschauen.

Viele Grüße

**Comment by kasek1975** [comment]
Ich warte heute das Devolo Update ab. Ein paar Fehler die ich dem Support gemeldet hatte sollen beseitigt werden. Ansonsten teste ich die anderen Punkte am Wochenende und melde mich.

**Comment by kantnschleifr** [comment]
Hi,
Ich habe seit gestern genau das gleiche Problem. 
Eines meiner zwei Garagentore wird in HomeKit nicht mehr aktualisiert. 
Beide Sensoren funktionierten die Monate davor ohne Probleme. 
Ist die Ursache möglicherweise in dem gestern von Devolo zwangsinstallierten Update zu sehen?
Reboot/restart von homebridge, devolo basis und meinen IOS Geräten brachte keine Veränderung.

**Comment by nicoh88** [comment]
Hi @kantnschleifr 

1. Werden die Stati im Devolo beim Tür-/Fensterkontakt korrekt angezeigt?
2. Werden die Stati im HomeKit beim Tür-/Fensterkontakt (nicht beim Garagentor) korrekt angezeigt?
3. Wie sieht die Homebridge-Log-Datei aus?

Viele Grüße

**Comment by kantnschleifr** [comment]
Hi @nicoh88 
Bin diese Woche unterwegs, deshalb erstmal die Antworten zu 1) + 2)
Zu 1) In der Devolo App ist alles korrekt. Beide Tore werden als geschlossen angezeigt. 
Zu 2) In Homekit: 
           erstes Tor: Status des Kontaktsensors: „geöffnet“ —> tatsächlich ist es geschlossen. 
           zweites Tor: Status des Kontaktsensors: „geschlossen“  —>  das ist richtig, es ist geschlossen.

Hatte heute früh nochmals beide Tore geöffnet und wieder geschlossen. 
Danke.

**Comment by kasek1975** [comment]
Ich habe mir das auch mal bei mir genauer angesehen. Vor dem Devolo Update hatte ich das Problem, dass Steckdosen in der App als angeschaltet angezeigt wurden und diese in der Realität aus war und umgekehrt. Dieses sollte mit dem letzten Update beseitigt sein - so die Info von devolo, da ich das gemeldet hatte.

Vorher hatte ich mit dem Tür-/Fensterkontakt an meiner Garage aber auch schon Probleme, dass der Status nicht aktualisiert wurde. Das Tor war offen, in der Devolo App wurde es auch so angezeigt in Homekit war es geschlossen.

An meiner Haustür habe ich einen  weiteren Kontakt, der nie Probleme gemacht hat.

Aktuell passt jetzt die Anzeige der Steckdosen und Rolläden zumindest in der Realität und in der devolo App.

In Homekit habe ich mir das heute angesehen, wenn ich die Übersicht (Raum) offen habe in dem Tür-/Fensterkontakt angezeigt wird, dann zeigt dieser an, wenn ich Tür oder Tor öffne. Wenn ich dann das iPhone schließe und wieder in direkt die Übersicht sehe, dann ist  die Tür oder das Tor, auch wenn es offen ist als geschlossen dargestellt. Nochmaliges schließen und öffnen zeigt dann den Status nach dem Aktualisieren wieder an. 

Zumindet bei mir hat das Devolo Update scheinbar dazu geführt, dass beide Kontakte gleich sind.

@kantnschleifr ich habe bei meinem Tor bemerkt, dass der Schalter auf der Rückseite des Kontaktes gerade in einem kleinen Loch an der Wand lag und somit nicht komplett gedrückt war. Keine Ahnung ob das seitens devolo abgefragt wird. Ich habe den Kontakt daraufhin etwas versetzt - ob es jetzt nur am Update oder auch daran lag, kann ich nicht sagen, Aber darauf hinweisen wollte ich zumindest mal.

**Comment by nicoh88** [comment]
> In Homekit habe ich mir das heute angesehen, wenn ich die Übersicht (Raum) offen habe in dem Tür-/Fensterkontakt angezeigt wird, dann zeigt dieser an, wenn ich Tür oder Tor öffne. Wenn ich dann das iPhone schließe und wieder in direkt die Übersicht sehe, dann ist die Tür oder das Tor, auch wenn es offen ist als geschlossen dargestellt. Nochmaliges schließen und öffnen zeigt dann den Status nach dem Aktualisieren wieder an.

@kasek1975: **Super recherchiert und prima für mich nachvollziehbar.** 

Habe es hier gerade nachgestellt und kann das Problem bestätigen! Werde es die nächsten Tage beheben und mich wieder melden. So muss das sein! Danke

**Comment by kantnschleifr** [comment]
@kasek1975 das mit dem rückwärtigen Schalter ist ein guter Hinweis. Werde ich anschauen, sobald ich wieder zu Hause bin (frühestens sonntags)
Danke.

**Comment by kasek1975** [comment]
@nicoh88: Danke! Genauso muss es sein! Super wenn es dir bei der Korrektur hilft!

@kantnschleifr: Gerne, bin gespannt

**Comment by kantnschleifr** [comment]
Wie versprochen hier mein update...
- Beim Öffnen und Schließen des Tores leuchtet die LED nicht.
- Der rückwärtige Schalter liegt auf, soweit ich das feststellen konnte.
- Irgendwie habe ich wohl versehentlich auf diesen Schalter gedrückt; danach war der Türkontakt auch in der Devolo-App als "offline" gekennzeichnet und hat nicht mehr reagiert.

Daraufhin habe ich den Türkontakt komplett aus  der DevoloHome-Installation gelöscht, komplett resetted und wieder aufgenommen. Danach leuchtete die LED wieder beim Schließen/Öffnen.
Nach einem weiteren Reboot des Raspi (inkl. Homebridge) und bouncen der Devolo-Homecontrol Basis scheint nun erstmal(?) alles wieder zu funktionieren.

**Comment by kantnschleifr** [comment]
Leider zu früh gefreut...
Ich war gerade nochmals draußen und habe festgestellt, dass das Tor "offen" ist, obwohl in HomeKit/Homebridge als "geschlossen" angezeigt.
Die Devolo-App hat zeigt es korrekt als "offen" dargestellt.

**Comment by nicoh88** [comment]
Hi @kasek1975 @kantnschleifr,

bitte mal die aktuelle GitHub-Master-Version testen ...

```
sudo su -
npm install kdietrich/homebridge-devolo#master -g --unsafe-perm
```

... und `homebridge` neustarten.

**Comment by kasek1975** [comment]
Sieht super aus! Habe gleich noch die neue nmp Version installiert, dass den GitHub-Master.
Bei beiden Tür-/Fensterkontakten wird jetzt der richtige Status angezeigt, selbst wenn ich den Bildschrim auf dem Handy Sperre. Schließe oder öffne ich dann nach dem Entsperren direkt wieder wird dies auch direkt angezeigt.  @nicoh88 toll und schnell umgesetzt!

**Comment by kantnschleifr** [comment]
Hi, 
funktioniert bei mir auch. 
Hatte mehrere Male die Tore gemeinsam oder einzeln geschlossen und geöffnet und es funktionierte alles wunderbar.
Super gemacht. Vielen Dank.

**Comment by nicoh88** [comment]
Prima! Der Dank geht an @kdietrich

**Comment by kasek1975** [comment]
Vielen Dank!

**Comment by nicoh88** [comment]
Hi Jungs,

ich habe noch ein paar Änderungen vorgenommen und die Version **0.1.14** nun auf NPM gepushed. Wenn ihr zurück vom `#master` auf die offizielle NPM-Version wollt:

```
sudo su -
npm install -g homebridge-devolo@latest
```

Gruß Nico

**Comment by kasek1975** [comment]
Habe gleich das Update auf die 0.1.14 gemacht und mit der Haustür getestet, sieht gut aus.
Super gemacht die Herren, danke nochmal!

**Comment by kantnschleifr** [comment]
Habe die 0.1.14 installiert und es läuft alles prima.
Vielen Dank!.
