### ISSUE TITLE
Problem bei der Installation von Homebridge-devolo

### ISSUE THREAD

**Issue by lemisoft** [kdietrich/homebridge-devolo#54]
Hallo,

bei einer Aktualisierung meines PI lässt sich zwar die Homebridge problemlos installieren, jedoch bei Homebridge-devolo kommt die beiliegende Fehlermeldung - als Linux Newbee habe ich keine Ahnung, woran das liegen kann... Ist das ein Bug?

Viele Grüße,
Andreas 

![Screenshot](https://user-images.githubusercontent.com/29504081/56036542-63c0c500-5d2d-11e9-9441-f7964aa13caa.png)

**Comment by nicoh88** [comment]
`sudo su`

**Comment by lemisoft** [comment]
Danke für die schnelle Antwort... das führt leider zur gleichen Fehlermeldung...

**Comment by nicoh88** [comment]
Das ist seltsam.

**Comment by lemisoft** [comment]
Der sieht genauso aus (abgesehen von anderen temporären IDs in den Verzeichnisnamen). Hilft Dir das Log weiter? 

[Log Install Homebridge Devolo.txt](https://github.com/kdietrich/homebridge-devolo/files/3073469/Log.Install.Homebridge.Devolo.txt)

**Comment by nicoh88** [comment]
Nein, das hilft leider nicht.
Bisher haben bei deinem Problem die drei o.g. Befehle immer geholfen.

**Comment by nicoh88** [comment]
@lemisoft 

Hast du eine Lösung gefunden? Kann hier zu?

**Comment by lemisoft** [comment]
Hallo Nico,

leider nein. Es ist ominös... Ich saß mit einem Linux-Experten zusammen und wir haben folgendes gemacht / herausgefunden:

- Wir haben dem Zielverzeichnis (von der Wurzel aus) komplette Zugiffsrechte für alle gegebenen - um auszuschließen, dass es wirklich ein Rechteproblem ist.

- Den Befehl aus dem Script zum clonen, der den Fehler verursacht, haben wir manuell aus root ausgeführt. Da läuft er problemlos... (das npm mit dem Fehler wurde auch als root ausgeführt).

Ich bin weiter ziemlich ratlos... Bleibt wohl nur ein komplettes Neu-Aufsetzen des PI.

Viele Grüße,
Andreas 

 
-- 
lemisoft • Andreas Lehmann
Nymphenburger Str. 147 • 80634 München • Germany
Tel: +49-89-14729332 • Mobile: +49-172-8569069
Fax: +49-89-14729334 • http://www.lemisoft.de
Skype: lemisoft • Twitter: @lemisoft

**Comment by nicoh88** [comment]
```
sudo su -
chown -R root /root/.npm
npm install -g homebridge-devolo --unsafe-perm
```

Das `-` hinter dem `sudo su` ist wichtig!

**Comment by lemisoft** [comment]
Hi,

genial - „sudo su -„ war die Lösung. Ein ganz dickes Dankeschön! 

BTW: Die Danfoss-Thermostate gehen bei mir mit der aktuellen Dev-Version auch wieder.

Viele Grüße,
Andreas
 
-- 
lemisoft • Andreas Lehmann
Nymphenburger Str. 147 • 80634 München • Germany
Tel: +49-89-14729332 • Mobile: +49-172-8569069
Fax: +49-89-14729334 • http://www.lemisoft.de
Skype: lemisoft • Twitter: @lemisoft

**Comment by nicoh88** [comment]
@lemisoft

Das sagte ich ja von Anfang an. 🙈
Dann suche dir mal einen neuen „Linux-Experten“. 🤣
