### ISSUE TITLE
Homebridge Devolo Fehler

### ISSUE THREAD

**Issue by ghost** [kdietrich/homebridge-devolo#56]
Hi, nach einer Neuinstallation, da HAM nicht mehr aktualisiert hatte tritt nun der Fehler auf:
Könnt ihr mir bitte helfen, da ich nicht weiß, was ich falsch mache?
Es wurde alles genauso wie vorher eingetragen. Nur ab dem Zeitpunkt, wenn ich Uuid, Gateway und Passkey eintrage, kommt dieses Log:

host.server | 2019-05-19 18:28:56.909 | info | Restart adapter system.adapter.ham.0 because enabled
-- | -- | -- | --
host.server | 2019-05-19 18:28:56.909 | error | instance system.adapter.ham.0 terminated with code 0 (OK)
host.server | 2019-05-19 18:28:56.909 | error | Caught by controller[1]: at process._tickCallback (internal/process/next_tick.js:181:9)
host.server | 2019-05-19 18:28:56.909 | error | Caught by controller[1]: at _combinedTickCallback (internal/process/next_tick.js:139:11)
host.server | 2019-05-19 18:28:56.909 | error | Caught by controller[1]: at endReadableNT (_stream_readable.js:1064:12)
host.server | 2019-05-19 18:28:56.909 | error | Caught by controller[1]: at IncomingMessage.emit (events.js:208:7)
host.server | 2019-05-19 18:28:56.909 | error | Caught by controller[1]: at emitNone (events.js:111:20)
host.server | 2019-05-19 18:28:56.909 | error | Caught by controller[1]: at IncomingMessage.<anonymous> (/usr/lib/node_modules/homebridge-devolo/node_modules/node-devolo/dist/DevoloApi.js:69:21)
host.server | 2019-05-19 18:28:56.909 | error | Caught by controller[1]: at /usr/lib/node_modules/homebridge-devolo/node_modules/node-devolo/dist/DevoloApi.js:185:17
host.server | 2019-05-19 18:28:56.909 | error | Caught by controller[1]: at /usr/lib/node_modules/homebridge-devolo/node_modules/node-devolo/dist/Devolo.js:336:47
host.server | 2019-05-19 18:28:56.909 | error | Caught by controller[1]: TypeError: Cannot read property 'length' of undefined
host.server | 2019-05-19 18:28:56.908 | error | Caught by controller[0]: [2019-5-19 18:28:55] Plugin /opt/iobroker/node_modules/homebridge-plugin-wrapper package.json does not contain the keyword 'homebridge-plugin'.
ham.0 | 2019-05-19 18:28:56.409 | debug | Device > %s < is not supported (yet) or devolo has something changed. Open an issue on github and ask for adding it. > Model: %s > ProductID: %s > ProductTypeID: %s > Sensors: %s
ham.0 | 2019-05-19 18:28:56.409 | debug | Device > %s < is not supported (yet) or devolo has something changed. Open an issue on github and ask for adding it. > Model: %s > ProductID: %s > ProductTypeID: %s > Sensors: %s
ham.0 | 2019-05-19 18:28:56.409 | debug | Device > %s < is not supported (yet) or devolo has something changed. Open an issue on github and ask for adding it. > Model: %s > ProductID: %s > ProductTypeID: %s > Sensors: %s
ham.0 | 2019-05-19 18:28:56.409 | debug | Device > %s < is not supported (yet) or devolo has something changed. Open an issue on github and ask for adding it. > Model: %s > ProductID: %s > ProductTypeID: %s > Sensors: %s
ham.0 | 2019-05-19 18:28:56.409 | debug | Device > %s < is not supported (yet) or devolo has something changed. Open an issue on github and ask for adding it. > Model: %s > ProductID: %s > ProductTypeID: %s > Sensors: %s
ham.0 | 2019-05-19 18:28:55.787 | debug | [2019-5-19 18:28:55] [Devolo] HBDevoloPlatform > Central Unit found.
ham.0 | 2019-05-19 18:28:55.787 | debug | Websocket open
ham.0 | 2019-05-19 18:28:55.699 | debug | Trying to connect to socket.
ham.0 | 2019-05-19 18:28:55.609 | debug | [2019-5-19 18:28:55] Loading 0 accessories...
ham.0 | 2019-05-19 18:28:55.609 | debug | [2019-5-19 18:28:55] [Devolo] HBDevoloPlatform > Searching for Devolo Central Unit.
ham.0 | 2019-05-19 18:28:55.609 | debug | [2019-5-19 18:28:55] [Devolo] Initializing Devolo platform...
ham.0 | 2019-05-19 18:28:55.609 | debug | [2019-5-19 18:28:55] Loading 1 platforms...
ham.0 | 2019-05-19 18:28:55.609 | debug | [2019-5-19 18:28:55] ---
ham.0 | 2019-05-19 18:28:55.609 | debug | [2019-5-19 18:28:55] Registering platform 'homebridge-devolo.Devolo'
ham.0 | 2019-05-19 18:28:55.609 | debug | [2019-5-19 18:28:55] Loaded plugin: homebridge-devolo
ham.0 | 2019-05-19 18:28:55.467 | info | starting. Version 1.0.0 in /opt/iobroker/node_modules/iobroker.ham, node: v8.16.0
host.server | 2019-05-19 18:28:54.906 | info | instance system.adapter.ham.0 started with pid 14635
host.server | 2019-05-19 18:28:24.898 | info | Restart adapter system.adapter.ham.0 because enabled

**Comment by nicoh88** [comment]
`Device > %s < is not supported (yet) or devolo has something changed. Open an issue on github and ask for adding it. > Model: %s > ProductID: %s > ProductTypeID: %s > Sensors: %s`

Er findet 5 Geräte, aber diese 5 Geräte werden von `homebridge-devolo` nicht unterstützt. Komisch, dass er die Info der Geräte nicht an "`ham`" weiterleitet. (`%s`)

Wenn du `homebridge-devolo` normal, ohne `ham` startest, bekommen wir auch die Infos der 5 Geräte - ohne `%s`.

Scheinbar hat Devolo bei einigen Geräten die Gerätebezeichnung geändert, deshalb das Problem. Ich benötige aber die Infos von dir, damit ich das beheben kann.

---

`Loading 0 accessories...`

Scheinbar hast du nur die fünf nicht unterstützten Geräte im Devolo? Daher 0 Geräte!

---

Wie viele Geräte hast du und welche?

**Comment by christei21** [comment]
Hallo, vielen Dank für deine schnelle Antwort :)

Ich habe aktuell 9 Geräte an der Devolozentrale angemeldet.
3x Rollo von Fibaro
1x Messsteckdose von Devolo
1x Wassersensor von Devolo
2x Rauchmelder von Fibaro
1x Wand-Schalter von Devolo
1x Kontktsensor von Fibaro

somit vier Devologeräte. Ich denke auch das hat was mit dem Update vom Mai zu tun. Iobroker aktualisierte auch nicht mehr. Ging zuvor, Anfang Mai, noch einwandfrei.

Ich benötige hier Hilfe: Wie starte ich Homebridge ohne Ham? Bzw. was kann ich sonst noch machen um zu helfen?
IoBroker läuft auf einem Linuxserver.

**Comment by nicoh88** [comment]
Hi @christei21,

ich werde dich hierbei nicht unterstützen. Sorry.

Wenn man mir die benötigen Infos gibt, nehme ich gerne die Anpassungen vor, damit die Geräte wieder unterstützt werden - aber weitere Hilfe biete ich nicht an.

Offiziell Artikelbezeichnung, `Device`, `Model`, `ProductID`, `ProductTypeID` und `Sensors`.

[Hier war es vorbildlich.](https://github.com/kdietrich/homebridge-devolo/issues/44#issuecomment-493438471)

**Comment by eyk2000** [comment]
Hallo, ich habe genau zu diesem Thema in dem "Hier war es vorbildlich" Tread meine Geräte-Problematik geschrieben - Sorry, soll ich es hier noch einmal machen...?

**Comment by nicoh88** [comment]
User "_christei21_" nicht mehr bei GitHub - daher hier zu.
