### ISSUE TITLE
Qubino Flush 1D Unterputz Schalter ist wieder "Unknown"

### ISSUE THREAD

**Issue by eyk2000** [kdietrich/homebridge-devolo#57]
Hallo, ich noch mal.
Ich habe schon im homebridge-devolo Issue 2 Beiträge geschrieben und bin hier hoffentlich richtig. Seit dem letzten Update von Devolo sind die Flush 1D zwar über die Devolo-App und die Website der HC steuerbar, tauchen aber nicht bei HomeKit auf.
Die Fehlermeldung zu den Geräten habe ich schon gepostet.
Wird es dazu noch ein update 0.1.15 (?) geben....?

Vielen Dank für Die Bemühungen und den Support.

Ich kann es leider nicht und bin ehrfürchtiger Nutzer Eurer Arbeit.

**Comment by nicoh88** [comment]
Hallo @eyk2000,

wenn du die `0.1.15-dev` installierst wird der **Qubino Flush 1D** wieder funktionieren:

```
sudo su -
npm install kdietrich/homebridge-devolo#master -g --unsafe-perm
```

Viele Grüße
