### ISSUE TITLE
Devolo Rolladenunterputz auf x% 

### ISSUE THREAD

**Issue by kasek1975** [kdietrich/homebridge-devolo#59]
Ich melde mich mit einem neuen Issue, weil ich bereits die Beta der Devolo Firmware installiert habe. Mir fällt hierbei auf, dass alles soweit mit der Homebridge gut funktioniert, nur wenn man einen Rolladen nicht komplett schließt oder öffnet, sondern auf ggf. 50%, dann bekommt Homekit keine Rückmeldung, wenn die Stellung erreicht ist. Also die Rolläden sind entsprechend geöffnet, die Devolo App zeigt dies auch an, aber bei der Kachel in Homekit zeigt sich die Prozentzahl nicht, sondern nur der Kreis, der eine entsprechende Aktivität anzeigt. Schließe ich die Homekit App und öffne diese neu, dann wird bei manchen Rolläden die Prozentzahl dann angezeigt, bei manchen weiterhin nicht. Hier gehe ich dann in die Devolo App und stelle eine abweichende Prozentzahl ein, damit der Rolladen nochmal bewegt wird. Ist dies dann erreicht, kann ich dei Devolo App schließen und auch in Homekit wird der eingestellte Wert dann angezeigt. Dies zur Info, da ich mich so früh wie möglich melden wollte. An Devolo kannn ich hier nichts melden, da alles soweit gut funktioniert.

**Comment by nicoh88** [comment]
Hi 👋🏼, 

danke für die Info.
Da ich leider nicht die Beta-Firmware habe, musst du warten bis die Firmware offiziell für alle ausgerollt wird. So kann ich das Problem leider nicht nachvollziehen! :cry

Vielleicht kannst du es ja auch selber lösen? Würde mich über einen „Pull Request“ freuen.

Viele Grüße

**Comment by kasek1975** [comment]
Sorry, ich war ein paar Tage unterwegs....

Wenn Du mir sagst, wie ich einen "Pull Request" erstellen kann, mache ich das....

**Comment by nicoh88** [comment]
https://yangsu.github.io/pull-request-tutorial/
