### ISSUE TITLE
Kann homebridge-devolo nicht installieren

### ISSUE THREAD

**Issue by Egal77** [kdietrich/homebridge-devolo#6]
Hallo ich bekomme folgende Meldung.
Homebridge startet. Aber ich bekomme dein Plugin nicht installiert. 
Es wäre echt schön wenn ich das hinbekommen könnte. Das ist genau das was ich gesucht habe.
Bin Linux Anfänger.

**pi@Raspberry:~ $ sudo npm install -g homebridge-devolo**
npm WARN addRemoteGit Error: not found: git
npm WARN addRemoteGit     at F (/usr/local/lib/node_modules/npm/node_modules/which/which.js:63:19)
npm WARN addRemoteGit     at E (/usr/local/lib/node_modules/npm/node_modules/which/which.js:72:29)
npm WARN addRemoteGit     at /usr/local/lib/node_modules/npm/node_modules/which/which.js:81:16
npm WARN addRemoteGit     at /usr/local/lib/node_modules/npm/node_modules/which/node_modules/isexe/index.js:44:5
npm WARN addRemoteGit     at /usr/local/lib/node_modules/npm/node_modules/which/node_modules/isexe/access.js:8:5
npm WARN addRemoteGit     at FSReqWrap.oncomplete (fs.js:82:15)
npm WARN addRemoteGit  git+https://github.com/kdietrich/node-devolo.git#9ede8698815e9c11202c2e76c40aa3fbf069f000 resetting remote /root/.npm/_git-remotes/https-github-com-kdietrich-node-devolo-git-7a8de7d0 because of error: { [Error: not found: git] code: 'ENOGIT' }
npm ERR! git clone --template=/root/.npm/_git-remotes/_templates --mirror https://github.com/kdietrich/node-devolo.git /root/.npm/_git-remotes/https-github-com-kdietrich-node-devolo-git-7a8de7d0: undefined
npm ERR! git clone --template=/root/.npm/_git-remotes/_templates --mirror https://github.com/kdietrich/node-devolo.git /root/.npm/_git-remotes/https-github-com-kdietrich-node-devolo-git-7a8de7d0: undefined
npm ERR! Linux 4.4.50+
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "homebridge-devolo"
npm ERR! node v4.4.0
npm ERR! npm  v2.14.20
npm ERR! code ENOGIT

npm ERR! not found: git
npm ERR!
npm ERR! Failed using git.
npm ERR! This is most likely not a problem with npm itself.
npm ERR! Please check if you have git installed and in your PATH.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/pi/npm-debug.log

**Comment by kdietrich** [comment]
Siehst so aus als hättest du 'git' nicht installiert. Welche Distribution nutzt du? Installation sollte mit 'sudo apt-get install git' klappen.

**Comment by Egal77** [comment]
Genau das war das Problem
Mit 
sudo apt-get install git 
habe ich es gerade hinbekommen. 

Aber wenn ich jetzt homebridge starte dann bekomme ich keine Fehlermeldung, aber auf dem Iphone wird mir nichts angezeigt.

**Comment by Egal77** [comment]
Wenn ich homebridge jetzt starte kommt folgendes 
/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/node_modules/mdns/lib/advertisement.js:56
  dns_sd.DNSServiceRegister(self.serviceRef, flags, ifaceIdx, name,
         ^

Error: dns service error: name conflict
    at Error (native)
    at new Advertisement (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/node_modules/mdns/lib/advertisement.js:56:10)
    at Object.create [as createAdvertisement] (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/node_modules/mdns/lib/advertisement.js:64:10)
    at Advertiser.startAdvertising (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Advertiser.js:43:30)
    at Bridge.Accessory._onListening (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:539:20)
    at emitOne (events.js:77:13)
    at HAPServer.emit (events.js:169:7)
    at HAPServer._onListening (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:190:8)
    at emitOne (events.js:77:13)
    at EventedHTTPServer.emit (events.js:169:7)

**Comment by Egal77** [comment]
Läuft.... hatte Probleme aber es lag nicht an deinem Plugin.
Danke echt Top das Tool.
Aber leider nur Devolo Geräte sichtbar. Ich habe eine Fibaro 2x1,5 , der lässt sich leider nicht steuern bzw. taucht er unter ios gar nicht auf.
Gibt es einen Möglichkeit Szenen zu steuern?

Aber nochmal Danke für das Plugin .... tolle Arbeit. Genau das was ich gesucht habe.

**Comment by nicoh88** [comment]
Hi @Egal77,

du meinst den [Fibaro Relais Unterputzeinsatz 2 Schalter 1,5 kW, FIBEFGS-222](https://www.amazon.de/Fibaro-Relais-Unterputzeinsatz-Schalter-FIBEFGS-222/dp/B00WH0S8F0/) oder?

Sollte machbar sein, auf jeden Fall braucht @kdietrich da eine Debug-Log von dir. Eventuell muss er auch das Debug-Logging erweitern, damit er von diesem Gerät die Infos bekommt die er benötigt. Mal schauen was er meint. 👍 

In der Theorie hast du dann, für den Unterputzeinsatz, zwei Schalter in "Home" - ähnlich wie eine Schaltsteckdose von Devolo.

Gruß Nico

**Comment by Egal77** [comment]
Wie generiere ich den ein Debug-Log ?
Ich habe auch an Devolo die Tür und Fenstersensoren DCH-Z110 von D-Link angeschlossen, diese werden auch nicht angezeigt.

**Comment by Egal77** [comment]
Meine Homebridge stürtzt nach einiger Zeit ca 1 Stunde ab.
Bekomme das 

[3/12/2017, 12:03:50 PM] [Devolo] HBDevoloSwitchMeterDevice > CurrentConsumption 7 > 6
[3/12/2017, 12:03:56 PM] [Devolo] HBDevoloSwitchMeterDevice > CurrentConsumption 6 > 2.8
[3/12/2017, 12:03:59 PM] [Devolo] HBDevoloSwitchMeterDevice > CurrentConsumption 2.8 > 6.1
[3/12/2017, 12:04:05 PM] [Devolo] HBDevoloSwitchMeterDevice > CurrentConsumption 6.1 > 3.9
[3/12/2017, 12:04:08 PM] [Devolo] HBDevoloSwitchMeterDevice > CurrentConsumption 3.9 > 7.1
[3/12/2017, 12:04:14 PM] [Devolo] HBDevoloSwitchMeterDevice > CurrentConsumption 7.1 > 3.7
[3/12/2017, 12:04:17 PM] [Devolo] HBDevoloSwitchMeterDevice > CurrentConsumption 3.7 > 7.1

Was kann ich machen?
Denke es liegt am Plugin.

Habe der Raspberry mehrmals neu aufgestzt. Doch es kommt immer wieder zu dem Abbruch.
Ich komme nicht mehr weiter

**Comment by nicoh88** [comment]
Hi @Egal77,

du musst Homebridge mit "_-D_" starten - damit produziert Homebridge viele Zeilen Output. Am Ende des Befehls leitest du mit "_2>&1 > debug.log_" den gesamten Output in eine Textdatei (_debug.log_) um. Wenn dann Homebridge wieder abstürzt, lädst du hier oder über einen Clouddienst deiner Wahl die Logdatei hoch und @kdietrich kann dann diese genauer analysieren.

Beispiel: `homebridge -D 2>&1 > debug.log`"

Gruß

**Comment by Egal77** [comment]
Bin Linux anfäger....
wie öffne ich die Datei dann und wo in welchem Ordner wird die Datei dann abgelegt?

Danke für die Hilfe

**Comment by nicoh88** [comment]
Hmm, ich nehme an du nutzt [Raspian](https://www.raspbian.org/) oder?

Die Datei wird immer dort abgelegt, wo du dich um Terminalfenster befindest. Wenn du keinen Befehl wie "`cd`" (change Directory) ausgeführt hast und als "**pi**" angemeldet bist, dann wäre es standardmäßig "`/home/pi`", wenn du als "**root**" angemeldet bist dann "`/root`".

Der Befehl "pwd" würde dir den Ordner anzeigen in dem du dich befindest.

![bildschirmfoto 2017-03-12 um 14 30 37](https://cloud.githubusercontent.com/assets/264264/23832202/84564bbe-0730-11e7-88ea-051d3fadb509.png)


In diesen Ordner navigierst du, über die grafischen Oberfläche, und ziehst die Datei auf einen Stick oder nutzt den Browser unter Raspbian zum Upload.

Gruß

**Comment by Egal77** [comment]
Ich nutze Jessi lite.

Der Befehl führt zu einem Fehler homebridge -D 2>&1 > debug.log". Homebridge startet nicht.
Ich denke es liegt daran weil ich homebridge zu autostart nach folgender Anleitung gepackt habe.
https://wiki.fhem.de/wiki/Homebridge_einrichten

Ich muss Homebridge mit 
`sudo service homebridge start`
starten.

Auch wenn ich Homebridge stoppe lässt sich dein Befehl zwar ausführen führt aber zu fehlern die ich nicht sehe. Denn Hombridge startet nicht.

So sieht es im Terminal bei mir dann aus
*** WARNING *** The program 'node' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node>
*** WARNING *** The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node&f=DNSServiceRegister>


weiter macht er nicht

**Comment by nicoh88** [comment]
Das sollte so passen, der Rest steht in der Logdatei "debug.log". 👍 
Kannst du deine Devolo Geräte in der Home App steuern? Dann weist du, dass Homebridge läuft.

Alternativ könntest du `homebridge -D 2>&1 | tee debug.log` benutzen, dann sollte alles in der Logdatei stehen und im Terminal.

**Comment by Egal77** [comment]
So folgende Fehlermeldung bekomme ich 

`
[3/12/2017, 6:03:16 PM] [Devolo] HBDevoloPlatform > Beat: 1266
[3/12/2017, 6:03:17 PM] [Devolo] HBDevoloPlatform > Beat: 1267
[3/12/2017, 6:03:18 PM] [Devolo] HBDevoloPlatform > Beat: 1268
[3/12/2017, 6:03:19 PM] [Devolo] HBDevoloDoorWindowDevice > Hearbeat
[3/12/2017, 6:03:19 PM] [Devolo] HBDevoloSwitchMeterDevice (hdm:ZWave:EC5DE06F/39) > Hearbeat
[3/12/2017, 6:03:19 PM] [Devolo] HBDevoloCentralUnit > Heartbeat: 1263 done
/usr/local/lib/node_modules/homebridge-devolo/node_modules/node-devolo/dist/DevoloApi.js:182
            if (res.error) {
                   ^

TypeError: Cannot read property 'error' of undefined
    at /usr/local/lib/node_modules/homebridge-devolo/node_modules/node-devolo/dist/DevoloApi.js:182:20
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/homebridge-devolo/node_modules/node-devolo/dist/DevoloApi.js:71:17)
    at emitNone (events.js:86:13)
    at IncomingMessage.emit (events.js:185:7)
    at IncomingMessage.<anonymous> (_http_client.js:279:11)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
`

**Comment by kdietrich** [comment]
@Egal77 Sieht so aus als würde deine Devolo Zentrale teilweise keine Antwort senden und homebridge-devolo stürzt ab. Werde ich alsbald beheben.

**Comment by Egal77** [comment]
Super Danke dir. 
Habe mich auch ein bisschen auf Fehlersuche gemacht bzw. versucht die Homebridge im Debug Modus laufen zu lassen. 
Hier der Fehler 
`[Devolo] HBDevoloPlatform > Error: socket hang up
`

**Comment by kdietrich** [comment]
Ist in der neuesten Version behoben! 👍
