### ISSUE TITLE
HBOtherRelaySwitchXDevice.ts - Fehler bei Nutzung mit Home+ 4 und Fibaro Unterputzschalter

### ISSUE THREAD

**Issue by gwi2014** [kdietrich/homebridge-devolo#64]
Hallo,
ich habe noch ein kleines anderes Problem. Ich habe mehrere Fibaro Unterputzschalter verbaut (FGS-211, FGS-213 und FGS-221). Wenn ich einen davon in _[Home+ 4](https://hochgatterer.me/home/)_ öffne, dann stürzt Homebridge ab:

```
 [2020-1-8 21:56:06] Error: Device has no suitable sensor.
     at RelaySwitchXDevice.Device.getCurrentValue (/usr/lib/node_modules/homebridge-devolo/node_modules/node-devolo/dist/DevoloDevice.js:228:19)
     at Array.HBOtherRelaySwitchXDevice.getDevoloCurrentConsumption (/usr/lib/node_modules/homebridge-devolo/dist/devices/HBOtherRelaySwitchXDevice.js:88:60)
     at Characteristic.DevoloCurrentConsumption.emit (events.js:223:5)
     at Characteristic.DevoloCurrentConsumption.Characteristic.getValue (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Characteristic.js:164:10)
     at Bridge.<anonymous> (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:771:20)
     at Array.forEach (<anonymous>)
     at Bridge.Accessory._handleGetCharacteristics (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:735:8)
     at HAPServer.emit (events.js:223:5)
     at HAPServer._handleCharacteristics (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:928:10)
     at HAPServer.<anonymous> (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:209:39)
 [2020-1-8 21:56:06] Got SIGTERM, shutting down Homebridge...
 homebridge.service: Main process exited, code=exited, status=143/n/a
 homebridge.service: Failed with result 'exit-code'.
 homebridge.service: Service RestartSec=3s expired, scheduling restart.
```

Das lässt sich beheben in dem man in _Home+ 4_ den Schalter bearbeitet und diese drei Werte ausblendet:
- Devolo Current Consumption
- Devolo Total Consumption
- Devolo Total Consumption Since

Viele Grüße,
Guido

**Comment by gwi2014** [comment]
Nachtrag: Interessanterweise werden die Werte des jeweils ersten Schalters kurz angezeigt und in der Homecontrol Zentrale stehen diese Werte zur Verfügung:

- Leistung 16.2 W
- Gesamt 8.3 kWh
- seit 24.10.2017

**Comment by nicoh88** [comment]
Hi Guido,

oh, die Fibaro Unterputzschalter sollten ...

- Devolo Current Consumption
- Devolo Total Consumption
- Devolo Total Consumption Since

... garnicht anzeigen. Ich schaue mal, ob ich ohne Testgerät, das Problem lösen kann.

Gruß Nico

**Comment by gwi2014** [comment]
Hi Nico,

> Hmm, mein FGS-223 (Double Switch) zeigt die Daten korrekt an - nutze aber nicht Home+ 4 sondern Controller für HomeKit.
> 
> Eventuell ein Bug in Home+ 4?

Das will ich nicht auschließen. Eventuell fragt er ja für die beiden Switches einzeln an und HomeControl liefert den Wert nur für den ersten Switch?

> PS: Ich habe eine allgemeine Frage zu Home+ 4: Kann man die Übersichtsseite so anpassen, dass man auch Szenen steuern kann? Kann man Geräte ausblenden? Oder werden Raum für Raum alle Geräte angezeigt?

Ich fange gerade erst an, mich mit dem Thema zu beschäftigen. Auf den ersten Blick sehe ich nicht, dass man Szenen auf der Geräteseite anzeigen kann - zumindest auf dem iPhone, die iPad App habe ich noch nicht angeschaut. Geräte ausblenden, habe ich auch noch nicht geschaft, man kann aber die Räume zusammenklappen. Damit könnte man die Homecontrol Zentrale und die Hue Bridge in einen Dummy Raum legen. Das ist vermutlich aber auch nicht das, was du brauchst. Eventuell einfach mal bei @brutella direkt fragen.


Nochmal zurück zum Problem. Muss die Abfrage an dieser Stelle so hart scheitern oder könnte man dort einfach 0/null/nil/undefined oder etwas ähnliches zurückgeben?

Viele Grüße,
Guido

**Comment by nicoh88** [comment]
> Eventuell fragt er ja für die beiden Switches einzeln an und HomeControl liefert den Wert nur für den ersten Switch?
> Nochmal zurück zum Problem. Muss die Abfrage an dieser Stelle so hart scheitern oder könnte man dort einfach 0/null/nil/undefined oder etwas ähnliches zurückgeben?

Du hast Recht, dass könnte der Grund sein!
Das Problem tritt dann aber nur bei deinem FGS-221, mit zwei "Schaltern", auf oder?

Grund sollte dann sein, dass wir vor ein paar Monaten `HBOtherRelaySwitchXDevice.ts` angepasst haben, dass es egal ob, 1, 2, 3 oder X Schalter in einem Modul, flexibel reagiert.

Am einfachsten wäre, so würde ich es machen, "_Devolo Current Consumption_", "_Devolo Total Consumption_" und "_Devolo Total Consumption Since_" bei nicht Devolo Schaltern einfach komplett wegzulassen.

**Comment by gwi2014** [comment]
Hmm das ist mühsam :-I 

Es scheint tatsächlich daran zu liegen, dass bei dem einen Schalter nur ein _Meter Sensor_ da ist:

```json
{
        "UID": "hdm:ZWave:EXXXXXX/YY",
        "properties": {
            "pendingOperations": null,
            "batteryLow": false,
            "zoneId": "hz_8",
            "isSecurelyIncluded": false,
            "zone": "Vorraum",
            "prodTypeID": "0x0403",
            "statisticsUID": "st.hdm:ZWave:EXXXXXX/YY",
            "secureInclusionCode": 0,
            "prodID": "0x1000",
            "status": 2,
            "settingUIDs": [
                "gds.hdm:ZWave:EXXXXXX/YY",
                "cps.hdm:ZWave:EXXXXXX/YY"
            ],
            "manID": "0x010f",
            "batteryLevel": -1,
            "icon": "icon_48",
            "operationStatus": null,
            "description": null,
            "wrongDevicePaired": false,
            "isOwn": true,
            "deviceModelUID": "unk.model.On/Off:Power:Switch",
            "itemName": "Licht außen",
            "elementUIDs": [
                "devolo.BinarySwitch:hdm:ZWave:EXXXXXX/YY#1",
                "devolo.Meter:hdm:ZWave:EXXXXXX/YY#1",
                "devolo.BinarySwitch:hdm:ZWave:EXXXXXX/YY#2",
                "devolo.BinarySensor:hdm:ZWave:EXXXXXX/YY#Alarm(4)",
                "devolo.LastActivity:hdm:ZWave:EXXXXXX/YY#Alarm(4)",
                "devolo.BinarySensor:hdm:ZWave:EXXXXXX/YY#Alarm(8)",
                "devolo.LastActivity:hdm:ZWave:EXXXXXX/YY#Alarm(8)"
            ]
        },
        "attributes": {},
        "objectClass": [
            "com.devolo.fi.widget.DeviceWidget",
            "com.devolo.fi.widget.BaseWidget",
            "com.devolo.fi.widget.Widget",
            "com.devolo.fi.async.base.AsyncFunctionalItem",
            "com.prosyst.mbs.services.fim.FunctionalItem"
        ],
        "tags": []
}
```

und die UID endet mit `#1` damit scheitert er in diesem Fall. Die anderen beiden Schalter haben gar kein Meter Sensor.

Aktuell neige ich dazu im Fehlerfall einfach 0 zurück zu geben. Spricht da etwas dagegen?

Und noch eine Frage: Kann ich hier einfach in einen neuen Branch pushen und dann einen PR erstellen?

Danke für die Hilfe,
Guido

**Comment by nicoh88** [comment]
@gwi2014 

> Aktuell neige ich dazu im Fehlerfall einfach 0 zurück zu geben. Spricht da etwas dagegen?

Kannst du gerne probieren!

> Und noch eine Frage: Kann ich hier einfach in einen neuen Branch pushen und dann einen PR erstellen?

Erstellt dir einfach ein Fork, mache da die Änderungen, installiere deine Version über npm zum Testen und wenn es funktioniert, erstellst du den PR. 👍 

Viele Grüße

**Comment by gwi2014** [comment]
@nicoh88 

Ich habe kdietrich/node-devolo/pull/3 erstellt. Diese Version würde ich dann gerne für den Fix hier verwenden. Kannst Du das mergen? Ich würde dann das package.json gleich entsprechend anpassen und mit in den PR packen.

Danke,
Guido

**Comment by nicoh88** [comment]
Cool! Hast du es getestet?

**Comment by gwi2014** [comment]
> Cool! Hast du es getestet?

Naja - "works for me" :grinning: - das ist ja erstmal nur die Vorarbeit. Die eigentlich Fix kommt ja erst, wenn ich den PR hier erstelle. Ich glaube aber, ich habe jetzt eine ganz gute Lösung gefunden.

**Comment by nicoh88** [comment]
Ok, alles klar. Dann warte ich noch mit dem `merge`, wenn alles fertig ist und du ordentlich getestet hast. :-)

**Comment by gwi2014** [comment]
Oh, da haben wir uns falsch verstanden. Ich brauche den Merge in `node-devolo` um dann hier in `homebridge-devolo` in package.json auf die neue Version referenzieren zu können. Ich könnte zwar auch auf meinen Fork verweisen, das macht aber IMO keinen Sinn.
Die Änderung in `node-devolo` ist relativ klein und da nur ein neues Property eingeführt wird, sollte das auch keine negativen Auswirkungen haben.

Zum Thema _ordentlich testen_ - mehr als das bei mir installieren und schauen, dass keine Fehler auftreten, kann ich doch nicht tun oder? Gibt es irgendwo Tests die ich ausführen kann?

**Comment by nicoh88** [comment]
> Oh, da haben wir uns falsch verstanden. Ich brauche den Merge in `node-devolo` um dann hier in `homebridge-devolo` in package.json auf die neue Version referenzieren zu können. Ich könnte zwar auch auf meinen Fork verweisen, das macht aber IMO keinen Sinn.
> Die Änderung in `node-devolo` ist relativ klein und da nur ein neues Property eingeführt wird, sollte das auch keine negativen Auswirkungen haben.

Merge, erledigt.


> Zum Thema _ordentlich testen_ - mehr als das bei mir installieren und schauen, dass keine Fehler auftreten, kann ich doch nicht tun oder? Gibt es irgendwo Tests die ich ausführen kann?

Korrekt! Mehr kannst du nicht tun.

**Comment by gwi2014** [comment]
Danke fürs mergen. Ich habe #65 für den eigentlichen Fix erstellt. Sorry für die dist/* Files, meine tsc Version (3.7.4) erstellt die .js Files offenbar etwas anders.

**Comment by nicoh88** [comment]
Kein Problem.
Danke für die Mitarbeit am Plugin!

MERGED! 🎉

Viele Grüße

**Comment by gwi2014** [comment]
Super, danke - #63 schaue ich mir am Wochenende mal an ...

**Comment by Beturi** [comment]
Klasse 👍 und  vielen Dank für die schnelle Rückmeldung und Reaktion!
