### ISSUE TITLE
Error: socket hang up

### ISSUE THREAD

**Issue by nicoh88** [kdietrich/homebridge-devolo#7]
Hallo Kevin,

wenn beispielsweise der Router neugestartet wird und die Komponenten (Devolo Zentrale, Homebridge-Server) nicht an einem externen Switch hängen oder per WLAN verbunden sind, dann kommt die Fehlermeldung "_Error: socket hang up_". Homebridge läuft weiter, aber das Devolo Plugin funktioniert nicht mehr.

```
homebridge[10089]: [2017-04-12 09:14:27] [Devolo] { Error: socket hang up
homebridge[10089]: at createHangUpError (_http_client.js:252:15)
homebridge[10089]: at Socket.socketCloseListener (_http_client.js:284:23)
homebridge[10089]: at emitOne (events.js:101:20)
homebridge[10089]: at Socket.emit (events.js:188:7)
homebridge[10089]: at TCP._handle.close [as _onclose] (net.js:492:12) code: 'ECONNRESET' }
```

Eventuell ein ReConnect nach 10, 30, 60, 120 und 300 Sekunden einbauen?

Gruß Nico

**Comment by kdietrich** [comment]
Thanks for reporting. Fixed with https://github.com/kdietrich/homebridge-devolo/commit/c14fb3a11e0116be616bc8cf8d5f88301f1489e2.
